/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BasicJSONMessage } from '../models';
// @ts-ignore
import { InlineResponseDefault } from '../models';
// @ts-ignore
import { KubernetesListResourceInYamlOutput } from '../models';
// @ts-ignore
import { ReleaseRelease } from '../models';
// @ts-ignore
import { TypesAppDeleteRequest } from '../models';
// @ts-ignore
import { TypesAppDeleteResponse } from '../models';
// @ts-ignore
import { TypesAppDeployRequest } from '../models';
// @ts-ignore
import { TypesToolDeleteRequest } from '../models';
// @ts-ignore
import { V1AppSecretRequest } from '../models';
// @ts-ignore
import { V1ConnectionResponse } from '../models';
// @ts-ignore
import { V1GetApplicationDetailsHasuraRequest } from '../models';
// @ts-ignore
import { V1GetApplicationDetailsResponse } from '../models';
// @ts-ignore
import { V1InstallCapsulesBody } from '../models';
// @ts-ignore
import { V1Pod } from '../models';
// @ts-ignore
import { V1PodList } from '../models';
// @ts-ignore
import { V1Secret } from '../models';
/**
 * V1AppApi - axios parameter creator
 * @export
 */
export const V1AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes an app
         * @param {TypesAppDeleteRequest} body App delete request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDelete: async (body: TypesAppDeleteRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('appDelete', 'body', body)
            const localVarPath = `/appDelete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deploys an app using the art.yaml file
         * @param {TypesAppDeployRequest} body App deploy request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDeploy: async (body: TypesAppDeployRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('appDeploy', 'body', body)
            const localVarPath = `/appDeploy`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restarts the app in a rolling fashion
         * @param {string} environmentName Environment name
         * @param {string} environmentRegion Environment region
         * @param {string} clusterName Name of the cluster
         * @param {string} appName Name of the app
         * @param {string} appType App Type enum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appRestart: async (environmentName: string, environmentRegion: string, clusterName: string, appName: string, appType: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'environmentName' is not null or undefined
            assertParamExists('appRestart', 'environmentName', environmentName)
            // verify required parameter 'environmentRegion' is not null or undefined
            assertParamExists('appRestart', 'environmentRegion', environmentRegion)
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('appRestart', 'clusterName', clusterName)
            // verify required parameter 'appName' is not null or undefined
            assertParamExists('appRestart', 'appName', appName)
            // verify required parameter 'appType' is not null or undefined
            assertParamExists('appRestart', 'appType', appType)
            const localVarPath = `/app/restart/{environment_name}/{environment_region}/{cluster_name}/{app_name}/{app_type}`
                .replace(`{${"environment_name"}}`, encodeURIComponent(String(environmentName)))
                .replace(`{${"environment_region"}}`, encodeURIComponent(String(environmentRegion)))
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"app_name"}}`, encodeURIComponent(String(appName)))
                .replace(`{${"app_type"}}`, encodeURIComponent(String(appType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretDelete: async (body: V1AppSecretRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('appSecretDelete', 'body', body)
            const localVarPath = `/app/secret/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretGet: async (body: V1AppSecretRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('appSecretGet', 'body', body)
            const localVarPath = `/app/secret/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates/Updates app secret with the name `art-{appName}-secret`
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretSet: async (body: V1AppSecretRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('appSecretSet', 'body', body)
            const localVarPath = `/app/secret/set`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the token for the cluster
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationTokenForCluster: async (clusterName: string, clusterRegion: string, namespace?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('authenticationTokenForCluster', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('authenticationTokenForCluster', 'clusterRegion', clusterRegion)
            const localVarPath = `/auth-token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (clusterName !== undefined) {
                localVarQueryParameter['cluster_name'] = clusterName;
            }

            if (clusterRegion !== undefined) {
                localVarQueryParameter['cluster_region'] = clusterRegion;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod that needs to be deleted
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePod: async (clusterName: string, clusterRegion: string, podName: string, namespace?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('deletePod', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('deletePod', 'clusterRegion', clusterRegion)
            // verify required parameter 'podName' is not null or undefined
            assertParamExists('deletePod', 'podName', podName)
            const localVarPath = `/pods/delete/{cluster_name}/{cluster_region}/{pod_name}`
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"cluster_region"}}`, encodeURIComponent(String(clusterRegion)))
                .replace(`{${"pod_name"}}`, encodeURIComponent(String(podName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Application Details will return the list of the following `PodStruct`, `ServiceStruct`,`SecretStruct`, `ConfigMapStruct`, `PersistentVolumeStruct`, `DaemonSetStruct` `StatefulSetStruct`, and `DeploymentStruct`. 
         * @summary Get all the details for a given application in a cluster
         * @param {V1GetApplicationDetailsHasuraRequest} body Get Application Details Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicationDetails: async (body: V1GetApplicationDetailsHasuraRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('getApplicationDetails', 'body', body)
            const localVarPath = `/getApplicationDetails`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Shows the pod information
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPod: async (clusterName: string, clusterRegion: string, podName: string, namespace?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('getPod', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('getPod', 'clusterRegion', clusterRegion)
            // verify required parameter 'podName' is not null or undefined
            assertParamExists('getPod', 'podName', podName)
            const localVarPath = `/pods/get/{cluster_name}/{cluster_region}/{pod_name}`
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"cluster_region"}}`, encodeURIComponent(String(clusterRegion)))
                .replace(`{${"pod_name"}}`, encodeURIComponent(String(podName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all the pods for the given deployment
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set'} resourceType Type of the resource we need to search the pods for
         * @param {string} resourceName Deployment name for which the pods are to be searched for
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPodsForDeployment: async (clusterName: string, clusterRegion: string, resourceType: 'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set', resourceName: string, namespace?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('getPodsForDeployment', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('getPodsForDeployment', 'clusterRegion', clusterRegion)
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('getPodsForDeployment', 'resourceType', resourceType)
            // verify required parameter 'resourceName' is not null or undefined
            assertParamExists('getPodsForDeployment', 'resourceName', resourceName)
            const localVarPath = `/pods/list/{cluster_name}/{cluster_region}/{resource_type}/{resource_name}`
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"cluster_region"}}`, encodeURIComponent(String(clusterRegion)))
                .replace(`{${"resource_type"}}`, encodeURIComponent(String(resourceType)))
                .replace(`{${"resource_name"}}`, encodeURIComponent(String(resourceName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all the resource description in yaml format
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {Array<string>} resourceType Type of the resource to include
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listResourceInYaml: async (clusterName: string, clusterRegion: string, resourceType: Array<string>, namespace?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('listResourceInYaml', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('listResourceInYaml', 'clusterRegion', clusterRegion)
            // verify required parameter 'resourceType' is not null or undefined
            assertParamExists('listResourceInYaml', 'resourceType', resourceType)
            const localVarPath = `/list-resources/{cluster_name}/{cluster_region}`
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"cluster_region"}}`, encodeURIComponent(String(clusterRegion)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (resourceType) {
                localVarQueryParameter['resource_type'] = resourceType.join(COLLECTION_FORMATS.csv);
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Shows the logs of the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {number} [sinceSeconds] limits the logs to given seconds
         * @param {number} [tailLines] limits the logs to given number of lines, counting from the lastest log line
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logPod: async (clusterName: string, clusterRegion: string, podName: string, namespace?: string, sinceSeconds?: number, tailLines?: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterName' is not null or undefined
            assertParamExists('logPod', 'clusterName', clusterName)
            // verify required parameter 'clusterRegion' is not null or undefined
            assertParamExists('logPod', 'clusterRegion', clusterRegion)
            // verify required parameter 'podName' is not null or undefined
            assertParamExists('logPod', 'podName', podName)
            const localVarPath = `/pods/logs/{cluster_name}/{cluster_region}/{pod_name}`
                .replace(`{${"cluster_name"}}`, encodeURIComponent(String(clusterName)))
                .replace(`{${"cluster_region"}}`, encodeURIComponent(String(clusterRegion)))
                .replace(`{${"pod_name"}}`, encodeURIComponent(String(podName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            if (sinceSeconds !== undefined) {
                localVarQueryParameter['sinceSeconds'] = sinceSeconds;
            }

            if (tailLines !== undefined) {
                localVarQueryParameter['tailLines'] = tailLines;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete tools from supported library
         * @param {TypesToolDeleteRequest} body Tools Delete Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toolDeleteFromLibrary: async (body: TypesToolDeleteRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('toolDeleteFromLibrary', 'body', body)
            const localVarPath = `/tools/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Install tools from the supported library
         * @param {V1InstallCapsulesBody} body Tools Install Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toolInstallFromLibrary: async (body: V1InstallCapsulesBody, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('toolInstallFromLibrary', 'body', body)
            const localVarPath = `/toolInstall`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWTKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * V1AppApi - functional programming interface
 * @export
 */
export const V1AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = V1AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deletes an app
         * @param {TypesAppDeleteRequest} body App delete request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appDelete(body: TypesAppDeleteRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TypesAppDeleteResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appDelete(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deploys an app using the art.yaml file
         * @param {TypesAppDeployRequest} body App deploy request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appDeploy(body: TypesAppDeployRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleaseRelease>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appDeploy(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Restarts the app in a rolling fashion
         * @param {string} environmentName Environment name
         * @param {string} environmentRegion Environment region
         * @param {string} clusterName Name of the cluster
         * @param {string} appName Name of the app
         * @param {string} appType App Type enum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appRestart(environmentName: string, environmentRegion: string, clusterName: string, appName: string, appType: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appRestart(environmentName, environmentRegion, clusterName, appName, appType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appSecretDelete(body: V1AppSecretRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Secret>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appSecretDelete(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Return the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appSecretGet(body: V1AppSecretRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Secret>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appSecretGet(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Creates/Updates app secret with the name `art-{appName}-secret`
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appSecretSet(body: V1AppSecretRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Secret>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appSecretSet(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get the token for the cluster
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authenticationTokenForCluster(clusterName: string, clusterRegion: string, namespace?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authenticationTokenForCluster(clusterName, clusterRegion, namespace, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod that needs to be deleted
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BasicJSONMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePod(clusterName, clusterRegion, podName, namespace, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get Application Details will return the list of the following `PodStruct`, `ServiceStruct`,`SecretStruct`, `ConfigMapStruct`, `PersistentVolumeStruct`, `DaemonSetStruct` `StatefulSetStruct`, and `DeploymentStruct`. 
         * @summary Get all the details for a given application in a cluster
         * @param {V1GetApplicationDetailsHasuraRequest} body Get Application Details Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getApplicationDetails(body: V1GetApplicationDetailsHasuraRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1GetApplicationDetailsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getApplicationDetails(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Shows the pod information
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Pod>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPod(clusterName, clusterRegion, podName, namespace, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all the pods for the given deployment
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set'} resourceType Type of the resource we need to search the pods for
         * @param {string} resourceName Deployment name for which the pods are to be searched for
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPodsForDeployment(clusterName: string, clusterRegion: string, resourceType: 'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set', resourceName: string, namespace?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1PodList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPodsForDeployment(clusterName, clusterRegion, resourceType, resourceName, namespace, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get all the resource description in yaml format
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {Array<string>} resourceType Type of the resource to include
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listResourceInYaml(clusterName: string, clusterRegion: string, resourceType: Array<string>, namespace?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KubernetesListResourceInYamlOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listResourceInYaml(clusterName, clusterRegion, resourceType, namespace, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Shows the logs of the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {number} [sinceSeconds] limits the logs to given seconds
         * @param {number} [tailLines] limits the logs to given number of lines, counting from the lastest log line
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logPod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, sinceSeconds?: number, tailLines?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logPod(clusterName, clusterRegion, podName, namespace, sinceSeconds, tailLines, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete tools from supported library
         * @param {TypesToolDeleteRequest} body Tools Delete Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toolDeleteFromLibrary(body: TypesToolDeleteRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TypesAppDeleteRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toolDeleteFromLibrary(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Install tools from the supported library
         * @param {V1InstallCapsulesBody} body Tools Install Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toolInstallFromLibrary(body: V1InstallCapsulesBody, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ConnectionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toolInstallFromLibrary(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * V1AppApi - factory interface
 * @export
 */
export const V1AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = V1AppApiFp(configuration)
    return {
        /**
         * 
         * @summary Deletes an app
         * @param {TypesAppDeleteRequest} body App delete request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDelete(body: TypesAppDeleteRequest, options?: any): AxiosPromise<Array<TypesAppDeleteResponse>> {
            return localVarFp.appDelete(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deploys an app using the art.yaml file
         * @param {TypesAppDeployRequest} body App deploy request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appDeploy(body: TypesAppDeployRequest, options?: any): AxiosPromise<ReleaseRelease> {
            return localVarFp.appDeploy(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restarts the app in a rolling fashion
         * @param {string} environmentName Environment name
         * @param {string} environmentRegion Environment region
         * @param {string} clusterName Name of the cluster
         * @param {string} appName Name of the app
         * @param {string} appType App Type enum
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appRestart(environmentName: string, environmentRegion: string, clusterName: string, appName: string, appType: string, options?: any): AxiosPromise<string> {
            return localVarFp.appRestart(environmentName, environmentRegion, clusterName, appName, appType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretDelete(body: V1AppSecretRequest, options?: any): AxiosPromise<V1Secret> {
            return localVarFp.appSecretDelete(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretGet(body: V1AppSecretRequest, options?: any): AxiosPromise<V1Secret> {
            return localVarFp.appSecretGet(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates/Updates app secret with the name `art-{appName}-secret`
         * @param {V1AppSecretRequest} body App secret request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appSecretSet(body: V1AppSecretRequest, options?: any): AxiosPromise<V1Secret> {
            return localVarFp.appSecretSet(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the token for the cluster
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authenticationTokenForCluster(clusterName: string, clusterRegion: string, namespace?: string, options?: any): AxiosPromise<string> {
            return localVarFp.authenticationTokenForCluster(clusterName, clusterRegion, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod that needs to be deleted
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, options?: any): AxiosPromise<BasicJSONMessage> {
            return localVarFp.deletePod(clusterName, clusterRegion, podName, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Application Details will return the list of the following `PodStruct`, `ServiceStruct`,`SecretStruct`, `ConfigMapStruct`, `PersistentVolumeStruct`, `DaemonSetStruct` `StatefulSetStruct`, and `DeploymentStruct`. 
         * @summary Get all the details for a given application in a cluster
         * @param {V1GetApplicationDetailsHasuraRequest} body Get Application Details Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getApplicationDetails(body: V1GetApplicationDetailsHasuraRequest, options?: any): AxiosPromise<V1GetApplicationDetailsResponse> {
            return localVarFp.getApplicationDetails(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Shows the pod information
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, options?: any): AxiosPromise<V1Pod> {
            return localVarFp.getPod(clusterName, clusterRegion, podName, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all the pods for the given deployment
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set'} resourceType Type of the resource we need to search the pods for
         * @param {string} resourceName Deployment name for which the pods are to be searched for
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPodsForDeployment(clusterName: string, clusterRegion: string, resourceType: 'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set', resourceName: string, namespace?: string, options?: any): AxiosPromise<V1PodList> {
            return localVarFp.getPodsForDeployment(clusterName, clusterRegion, resourceType, resourceName, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all the resource description in yaml format
         * @param {string} clusterName Cluster name
         * @param {string} clusterRegion The region of the cluster
         * @param {Array<string>} resourceType Type of the resource to include
         * @param {string} [namespace] searches for in the namespace
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listResourceInYaml(clusterName: string, clusterRegion: string, resourceType: Array<string>, namespace?: string, options?: any): AxiosPromise<KubernetesListResourceInYamlOutput> {
            return localVarFp.listResourceInYaml(clusterName, clusterRegion, resourceType, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Shows the logs of the given pod in the (namespace, cluster, region)
         * @param {string} clusterName Cluster name in which the pods are to be searched for
         * @param {string} clusterRegion The region of the cluster
         * @param {string} podName Name of the pod
         * @param {string} [namespace] searches for in the namespace
         * @param {number} [sinceSeconds] limits the logs to given seconds
         * @param {number} [tailLines] limits the logs to given number of lines, counting from the lastest log line
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logPod(clusterName: string, clusterRegion: string, podName: string, namespace?: string, sinceSeconds?: number, tailLines?: number, options?: any): AxiosPromise<string> {
            return localVarFp.logPod(clusterName, clusterRegion, podName, namespace, sinceSeconds, tailLines, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete tools from supported library
         * @param {TypesToolDeleteRequest} body Tools Delete Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toolDeleteFromLibrary(body: TypesToolDeleteRequest, options?: any): AxiosPromise<Array<TypesAppDeleteRequest>> {
            return localVarFp.toolDeleteFromLibrary(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Install tools from the supported library
         * @param {V1InstallCapsulesBody} body Tools Install Request Body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toolInstallFromLibrary(body: V1InstallCapsulesBody, options?: any): AxiosPromise<V1ConnectionResponse> {
            return localVarFp.toolInstallFromLibrary(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for appDelete operation in V1AppApi.
 * @export
 * @interface V1AppApiAppDeleteRequest
 */
export interface V1AppApiAppDeleteRequest {
    /**
     * App delete request
     * @type {TypesAppDeleteRequest}
     * @memberof V1AppApiAppDelete
     */
    readonly body: TypesAppDeleteRequest
}

/**
 * Request parameters for appDeploy operation in V1AppApi.
 * @export
 * @interface V1AppApiAppDeployRequest
 */
export interface V1AppApiAppDeployRequest {
    /**
     * App deploy request
     * @type {TypesAppDeployRequest}
     * @memberof V1AppApiAppDeploy
     */
    readonly body: TypesAppDeployRequest
}

/**
 * Request parameters for appRestart operation in V1AppApi.
 * @export
 * @interface V1AppApiAppRestartRequest
 */
export interface V1AppApiAppRestartRequest {
    /**
     * Environment name
     * @type {string}
     * @memberof V1AppApiAppRestart
     */
    readonly environmentName: string

    /**
     * Environment region
     * @type {string}
     * @memberof V1AppApiAppRestart
     */
    readonly environmentRegion: string

    /**
     * Name of the cluster
     * @type {string}
     * @memberof V1AppApiAppRestart
     */
    readonly clusterName: string

    /**
     * Name of the app
     * @type {string}
     * @memberof V1AppApiAppRestart
     */
    readonly appName: string

    /**
     * App Type enum
     * @type {string}
     * @memberof V1AppApiAppRestart
     */
    readonly appType: string
}

/**
 * Request parameters for appSecretDelete operation in V1AppApi.
 * @export
 * @interface V1AppApiAppSecretDeleteRequest
 */
export interface V1AppApiAppSecretDeleteRequest {
    /**
     * App secret request body
     * @type {V1AppSecretRequest}
     * @memberof V1AppApiAppSecretDelete
     */
    readonly body: V1AppSecretRequest
}

/**
 * Request parameters for appSecretGet operation in V1AppApi.
 * @export
 * @interface V1AppApiAppSecretGetRequest
 */
export interface V1AppApiAppSecretGetRequest {
    /**
     * App secret request body
     * @type {V1AppSecretRequest}
     * @memberof V1AppApiAppSecretGet
     */
    readonly body: V1AppSecretRequest
}

/**
 * Request parameters for appSecretSet operation in V1AppApi.
 * @export
 * @interface V1AppApiAppSecretSetRequest
 */
export interface V1AppApiAppSecretSetRequest {
    /**
     * App secret request body
     * @type {V1AppSecretRequest}
     * @memberof V1AppApiAppSecretSet
     */
    readonly body: V1AppSecretRequest
}

/**
 * Request parameters for authenticationTokenForCluster operation in V1AppApi.
 * @export
 * @interface V1AppApiAuthenticationTokenForClusterRequest
 */
export interface V1AppApiAuthenticationTokenForClusterRequest {
    /**
     * Cluster name in which the pods are to be searched for
     * @type {string}
     * @memberof V1AppApiAuthenticationTokenForCluster
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiAuthenticationTokenForCluster
     */
    readonly clusterRegion: string

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiAuthenticationTokenForCluster
     */
    readonly namespace?: string
}

/**
 * Request parameters for deletePod operation in V1AppApi.
 * @export
 * @interface V1AppApiDeletePodRequest
 */
export interface V1AppApiDeletePodRequest {
    /**
     * Cluster name in which the pods are to be searched for
     * @type {string}
     * @memberof V1AppApiDeletePod
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiDeletePod
     */
    readonly clusterRegion: string

    /**
     * Name of the pod that needs to be deleted
     * @type {string}
     * @memberof V1AppApiDeletePod
     */
    readonly podName: string

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiDeletePod
     */
    readonly namespace?: string
}

/**
 * Request parameters for getApplicationDetails operation in V1AppApi.
 * @export
 * @interface V1AppApiGetApplicationDetailsRequest
 */
export interface V1AppApiGetApplicationDetailsRequest {
    /**
     * Get Application Details Request Body
     * @type {V1GetApplicationDetailsHasuraRequest}
     * @memberof V1AppApiGetApplicationDetails
     */
    readonly body: V1GetApplicationDetailsHasuraRequest
}

/**
 * Request parameters for getPod operation in V1AppApi.
 * @export
 * @interface V1AppApiGetPodRequest
 */
export interface V1AppApiGetPodRequest {
    /**
     * Cluster name
     * @type {string}
     * @memberof V1AppApiGetPod
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiGetPod
     */
    readonly clusterRegion: string

    /**
     * Name of the pod
     * @type {string}
     * @memberof V1AppApiGetPod
     */
    readonly podName: string

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiGetPod
     */
    readonly namespace?: string
}

/**
 * Request parameters for getPodsForDeployment operation in V1AppApi.
 * @export
 * @interface V1AppApiGetPodsForDeploymentRequest
 */
export interface V1AppApiGetPodsForDeploymentRequest {
    /**
     * Cluster name in which the pods are to be searched for
     * @type {string}
     * @memberof V1AppApiGetPodsForDeployment
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiGetPodsForDeployment
     */
    readonly clusterRegion: string

    /**
     * Type of the resource we need to search the pods for
     * @type {'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set'}
     * @memberof V1AppApiGetPodsForDeployment
     */
    readonly resourceType: 'daemon-set' | 'deployment' | 'stateful-set' | 'replica-set'

    /**
     * Deployment name for which the pods are to be searched for
     * @type {string}
     * @memberof V1AppApiGetPodsForDeployment
     */
    readonly resourceName: string

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiGetPodsForDeployment
     */
    readonly namespace?: string
}

/**
 * Request parameters for listResourceInYaml operation in V1AppApi.
 * @export
 * @interface V1AppApiListResourceInYamlRequest
 */
export interface V1AppApiListResourceInYamlRequest {
    /**
     * Cluster name
     * @type {string}
     * @memberof V1AppApiListResourceInYaml
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiListResourceInYaml
     */
    readonly clusterRegion: string

    /**
     * Type of the resource to include
     * @type {Array<string>}
     * @memberof V1AppApiListResourceInYaml
     */
    readonly resourceType: Array<string>

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiListResourceInYaml
     */
    readonly namespace?: string
}

/**
 * Request parameters for logPod operation in V1AppApi.
 * @export
 * @interface V1AppApiLogPodRequest
 */
export interface V1AppApiLogPodRequest {
    /**
     * Cluster name in which the pods are to be searched for
     * @type {string}
     * @memberof V1AppApiLogPod
     */
    readonly clusterName: string

    /**
     * The region of the cluster
     * @type {string}
     * @memberof V1AppApiLogPod
     */
    readonly clusterRegion: string

    /**
     * Name of the pod
     * @type {string}
     * @memberof V1AppApiLogPod
     */
    readonly podName: string

    /**
     * searches for in the namespace
     * @type {string}
     * @memberof V1AppApiLogPod
     */
    readonly namespace?: string

    /**
     * limits the logs to given seconds
     * @type {number}
     * @memberof V1AppApiLogPod
     */
    readonly sinceSeconds?: number

    /**
     * limits the logs to given number of lines, counting from the lastest log line
     * @type {number}
     * @memberof V1AppApiLogPod
     */
    readonly tailLines?: number
}

/**
 * Request parameters for toolDeleteFromLibrary operation in V1AppApi.
 * @export
 * @interface V1AppApiToolDeleteFromLibraryRequest
 */
export interface V1AppApiToolDeleteFromLibraryRequest {
    /**
     * Tools Delete Request Body
     * @type {TypesToolDeleteRequest}
     * @memberof V1AppApiToolDeleteFromLibrary
     */
    readonly body: TypesToolDeleteRequest
}

/**
 * Request parameters for toolInstallFromLibrary operation in V1AppApi.
 * @export
 * @interface V1AppApiToolInstallFromLibraryRequest
 */
export interface V1AppApiToolInstallFromLibraryRequest {
    /**
     * Tools Install Request Body
     * @type {V1InstallCapsulesBody}
     * @memberof V1AppApiToolInstallFromLibrary
     */
    readonly body: V1InstallCapsulesBody
}

/**
 * V1AppApi - object-oriented interface
 * @export
 * @class V1AppApi
 * @extends {BaseAPI}
 */
export class V1AppApi extends BaseAPI {
    /**
     * 
     * @summary Deletes an app
     * @param {V1AppApiAppDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appDelete(requestParameters: V1AppApiAppDeleteRequest, options?: any) {
        return V1AppApiFp(this.configuration).appDelete(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deploys an app using the art.yaml file
     * @param {V1AppApiAppDeployRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appDeploy(requestParameters: V1AppApiAppDeployRequest, options?: any) {
        return V1AppApiFp(this.configuration).appDeploy(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Restarts the app in a rolling fashion
     * @param {V1AppApiAppRestartRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appRestart(requestParameters: V1AppApiAppRestartRequest, options?: any) {
        return V1AppApiFp(this.configuration).appRestart(requestParameters.environmentName, requestParameters.environmentRegion, requestParameters.clusterName, requestParameters.appName, requestParameters.appType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
     * @param {V1AppApiAppSecretDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appSecretDelete(requestParameters: V1AppApiAppSecretDeleteRequest, options?: any) {
        return V1AppApiFp(this.configuration).appSecretDelete(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return the app secret if it exists otherwise returns an error saying the app secret doesn\'t exist
     * @param {V1AppApiAppSecretGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appSecretGet(requestParameters: V1AppApiAppSecretGetRequest, options?: any) {
        return V1AppApiFp(this.configuration).appSecretGet(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates/Updates app secret with the name `art-{appName}-secret`
     * @param {V1AppApiAppSecretSetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public appSecretSet(requestParameters: V1AppApiAppSecretSetRequest, options?: any) {
        return V1AppApiFp(this.configuration).appSecretSet(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the token for the cluster
     * @param {V1AppApiAuthenticationTokenForClusterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public authenticationTokenForCluster(requestParameters: V1AppApiAuthenticationTokenForClusterRequest, options?: any) {
        return V1AppApiFp(this.configuration).authenticationTokenForCluster(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.namespace, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes the given pod in the (namespace, cluster, region)
     * @param {V1AppApiDeletePodRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public deletePod(requestParameters: V1AppApiDeletePodRequest, options?: any) {
        return V1AppApiFp(this.configuration).deletePod(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.podName, requestParameters.namespace, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Application Details will return the list of the following `PodStruct`, `ServiceStruct`,`SecretStruct`, `ConfigMapStruct`, `PersistentVolumeStruct`, `DaemonSetStruct` `StatefulSetStruct`, and `DeploymentStruct`. 
     * @summary Get all the details for a given application in a cluster
     * @param {V1AppApiGetApplicationDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public getApplicationDetails(requestParameters: V1AppApiGetApplicationDetailsRequest, options?: any) {
        return V1AppApiFp(this.configuration).getApplicationDetails(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Shows the pod information
     * @param {V1AppApiGetPodRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public getPod(requestParameters: V1AppApiGetPodRequest, options?: any) {
        return V1AppApiFp(this.configuration).getPod(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.podName, requestParameters.namespace, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all the pods for the given deployment
     * @param {V1AppApiGetPodsForDeploymentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public getPodsForDeployment(requestParameters: V1AppApiGetPodsForDeploymentRequest, options?: any) {
        return V1AppApiFp(this.configuration).getPodsForDeployment(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.resourceType, requestParameters.resourceName, requestParameters.namespace, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all the resource description in yaml format
     * @param {V1AppApiListResourceInYamlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public listResourceInYaml(requestParameters: V1AppApiListResourceInYamlRequest, options?: any) {
        return V1AppApiFp(this.configuration).listResourceInYaml(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.resourceType, requestParameters.namespace, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Shows the logs of the given pod in the (namespace, cluster, region)
     * @param {V1AppApiLogPodRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public logPod(requestParameters: V1AppApiLogPodRequest, options?: any) {
        return V1AppApiFp(this.configuration).logPod(requestParameters.clusterName, requestParameters.clusterRegion, requestParameters.podName, requestParameters.namespace, requestParameters.sinceSeconds, requestParameters.tailLines, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete tools from supported library
     * @param {V1AppApiToolDeleteFromLibraryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public toolDeleteFromLibrary(requestParameters: V1AppApiToolDeleteFromLibraryRequest, options?: any) {
        return V1AppApiFp(this.configuration).toolDeleteFromLibrary(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Install tools from the supported library
     * @param {V1AppApiToolInstallFromLibraryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1AppApi
     */
    public toolInstallFromLibrary(requestParameters: V1AppApiToolInstallFromLibraryRequest, options?: any) {
        return V1AppApiFp(this.configuration).toolInstallFromLibrary(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}
