/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CapsulesConfigGrafana
 */
export interface CapsulesConfigGrafana {
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    accessKeyId?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    accessKeyIdBase64?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    domainName: string;
    /**
     * input
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    s3Bucket: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    s3region: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    secretAccessKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    secretAccessKeyBase64?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesConfigGrafana
     */
    username: string;
}


