/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CapsulesInputCustomApp
 */
export interface CapsulesInputCustomApp {
    /**
     * 
     * @type {string}
     * @memberof CapsulesInputCustomApp
     */
    appName?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesInputCustomApp
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof CapsulesInputCustomApp
     */
    repoUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof CapsulesInputCustomApp
     */
    values?: object;
}


