/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChartFile
 */
export interface ChartFile {
    /**
     * Data is the template as byte data.
     * @type {Array<number>}
     * @memberof ChartFile
     */
    data?: Array<number>;
    /**
     * Name is the path-like name of the template.
     * @type {string}
     * @memberof ChartFile
     */
    name?: string;
}


