/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChartDependency
 */
export interface ChartDependency {
    /**
     * Alias usable alias to be used for the chart
     * @type {string}
     * @memberof ChartDependency
     */
    alias?: string;
    /**
     * A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
     * @type {string}
     * @memberof ChartDependency
     */
    condition?: string;
    /**
     * Enabled bool determines if chart should be loaded
     * @type {boolean}
     * @memberof ChartDependency
     */
    enabled?: boolean;
    /**
     * ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
     * @type {Array<object>}
     * @memberof ChartDependency
     */
    import_values?: Array<object>;
    /**
     * Name is the name of the dependency.  This must mach the name in the dependency\'s Chart.yaml.
     * @type {string}
     * @memberof ChartDependency
     */
    name?: string;
    /**
     * The URL to the repository.  Appending `index.yaml` to this string should result in a URL that can be used to fetch the repository index.
     * @type {string}
     * @memberof ChartDependency
     */
    repository?: string;
    /**
     * Tags can be used to group charts for enabling/disabling together
     * @type {Array<string>}
     * @memberof ChartDependency
     */
    tags?: Array<string>;
    /**
     * Version is the version (range) of this chart.  A lock file will always produce a single version, while a dependency may contain a semantic version range.
     * @type {string}
     * @memberof ChartDependency
     */
    version?: string;
}


