/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EksNodegroupScalingConfig
 */
export interface EksNodegroupScalingConfig {
    /**
     * The current number of nodes that the managed node group should maintain.
     * @type {number}
     * @memberof EksNodegroupScalingConfig
     */
    desiredSize?: number;
    /**
     * The maximum number of nodes that the managed node group can scale out to. For information about the maximum number that you can specify, see Amazon EKS service quotas (https://docs.aws.amazon.com/eks/latest/userguide/service-quotas.html) in the Amazon EKS User Guide.
     * @type {number}
     * @memberof EksNodegroupScalingConfig
     */
    maxSize?: number;
    /**
     * The minimum number of nodes that the managed node group can scale in to. This number must be greater than zero.
     * @type {number}
     * @memberof EksNodegroupScalingConfig
     */
    minSize?: number;
}


