/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EksNodegroupUpdateConfig
 */
export interface EksNodegroupUpdateConfig {
    /**
     * The maximum number of nodes unavailable at once during a version update. Nodes will be updated in parallel. This value or maxUnavailablePercentage is required to have a value.The maximum number is 100.
     * @type {number}
     * @memberof EksNodegroupUpdateConfig
     */
    MaxUnavailable?: number;
    /**
     * The maximum percentage of nodes unavailable during a version update. This percentage of nodes will be updated in parallel, up to 100 nodes at once. This value or maxUnavailable is required to have a value.
     * @type {number}
     * @memberof EksNodegroupUpdateConfig
     */
    MaxUnavailablePercentage?: number;
}


