/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';
import { ElasticsearchserviceSnapshotOptions } from './elasticsearchservice-snapshot-options';

/**
 * 
 * @export
 * @interface ElasticsearchserviceSnapshotOptionsStatus
 */
export interface ElasticsearchserviceSnapshotOptionsStatus {
    /**
     * 
     * @type {ElasticsearchserviceSnapshotOptions}
     * @memberof ElasticsearchserviceSnapshotOptionsStatus
     */
    Options?: ElasticsearchserviceSnapshotOptions;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceSnapshotOptionsStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


