/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceNodeToNodeEncryptionOptions } from './elasticsearchservice-node-to-node-encryption-options';
import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceNodeToNodeEncryptionOptionsStatus
 */
export interface ElasticsearchserviceNodeToNodeEncryptionOptionsStatus {
    /**
     * 
     * @type {ElasticsearchserviceNodeToNodeEncryptionOptions}
     * @memberof ElasticsearchserviceNodeToNodeEncryptionOptionsStatus
     */
    Options?: ElasticsearchserviceNodeToNodeEncryptionOptions;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceNodeToNodeEncryptionOptionsStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


