/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceElasticsearchClusterConfig } from './elasticsearchservice-elasticsearch-cluster-config';
import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceElasticsearchClusterConfigStatus
 */
export interface ElasticsearchserviceElasticsearchClusterConfigStatus {
    /**
     * 
     * @type {ElasticsearchserviceElasticsearchClusterConfig}
     * @memberof ElasticsearchserviceElasticsearchClusterConfigStatus
     */
    Options?: ElasticsearchserviceElasticsearchClusterConfig;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceElasticsearchClusterConfigStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


