/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceAutoTuneStatus
 */
export interface ElasticsearchserviceAutoTuneStatus {
    /**
     * Timestamp which tells Auto-Tune options creation date .  CreationDate is a required field
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    CreationDate?: string;
    /**
     * Specifies the error message while enabling or disabling the Auto-Tune options.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    ErrorMessage?: string;
    /**
     * Indicates whether the Elasticsearch domain is being deleted.
     * @type {boolean}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    PendingDeletion?: boolean;
    /**
     * Specifies the AutoTuneState for the Elasticsearch domain.  State is a required field
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    State?: string;
    /**
     * Timestamp which tells Auto-Tune options last updated time.  UpdateDate is a required field
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    UpdateDate?: string;
    /**
     * Specifies the Auto-Tune options latest version.
     * @type {number}
     * @memberof ElasticsearchserviceAutoTuneStatus
     */
    UpdateVersion?: number;
}


