/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceSAMLIdp
 */
export interface ElasticsearchserviceSAMLIdp {
    /**
     * The unique Entity ID of the application in SAML Identity Provider.  EntityId is a required field
     * @type {string}
     * @memberof ElasticsearchserviceSAMLIdp
     */
    EntityId?: string;
    /**
     * The Metadata of the SAML application in xml format.  MetadataContent is a required field
     * @type {string}
     * @memberof ElasticsearchserviceSAMLIdp
     */
    MetadataContent?: string;
}


