/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceOptionStatus
 */
export interface ElasticsearchserviceOptionStatus {
    /**
     * Timestamp which tells the creation date for the entity.  CreationDate is a required field
     * @type {string}
     * @memberof ElasticsearchserviceOptionStatus
     */
    CreationDate?: string;
    /**
     * Indicates whether the Elasticsearch domain is being deleted.
     * @type {boolean}
     * @memberof ElasticsearchserviceOptionStatus
     */
    PendingDeletion?: boolean;
    /**
     * Provides the OptionState for the Elasticsearch domain.  State is a required field
     * @type {string}
     * @memberof ElasticsearchserviceOptionStatus
     */
    State?: string;
    /**
     * Timestamp which tells the last updated time for the entity.  UpdateDate is a required field
     * @type {string}
     * @memberof ElasticsearchserviceOptionStatus
     */
    UpdateDate?: string;
    /**
     * Specifies the latest version for the entity.
     * @type {number}
     * @memberof ElasticsearchserviceOptionStatus
     */
    UpdateVersion?: number;
}


