/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticacheCloudWatchLogsDestinationDetails } from './elasticache-cloud-watch-logs-destination-details';
import { ElasticacheKinesisFirehoseDestinationDetails } from './elasticache-kinesis-firehose-destination-details';

/**
 * 
 * @export
 * @interface ElasticacheDestinationDetails
 */
export interface ElasticacheDestinationDetails {
    /**
     * 
     * @type {ElasticacheCloudWatchLogsDestinationDetails}
     * @memberof ElasticacheDestinationDetails
     */
    cloudWatchLogsDetails?: ElasticacheCloudWatchLogsDestinationDetails;
    /**
     * 
     * @type {ElasticacheKinesisFirehoseDestinationDetails}
     * @memberof ElasticacheDestinationDetails
     */
    kinesisFirehoseDetails?: ElasticacheKinesisFirehoseDestinationDetails;
}


