/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceColdStorageOptions
 */
export interface ElasticsearchserviceColdStorageOptions {
    /**
     * Enable cold storage option. Accepted values true or false  Enabled is a required field
     * @type {boolean}
     * @memberof ElasticsearchserviceColdStorageOptions
     */
    Enabled?: boolean;
}


