/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceAccessPoliciesStatus
 */
export interface ElasticsearchserviceAccessPoliciesStatus {
    /**
     * The access policy configured for the Elasticsearch domain. Access policies may be resource-based, IP-based, or IAM-based. See Configuring Access Policies (http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies)for more information.  Options is a required field
     * @type {string}
     * @memberof ElasticsearchserviceAccessPoliciesStatus
     */
    Options?: string;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceAccessPoliciesStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


