/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceColdStorageOptions } from './elasticsearchservice-cold-storage-options';
import { ElasticsearchserviceZoneAwarenessConfig } from './elasticsearchservice-zone-awareness-config';

/**
 * 
 * @export
 * @interface ElasticsearchserviceElasticsearchClusterConfig
 */
export interface ElasticsearchserviceElasticsearchClusterConfig {
    /**
     * 
     * @type {ElasticsearchserviceColdStorageOptions}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    ColdStorageOptions?: ElasticsearchserviceColdStorageOptions;
    /**
     * Total number of dedicated master nodes, active and on standby, for the cluster.
     * @type {number}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    DedicatedMasterCount?: number;
    /**
     * A boolean value to indicate whether a dedicated master node is enabled. See About Dedicated Master Nodes (http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-dedicatedmasternodes) for more information.
     * @type {boolean}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    DedicatedMasterEnabled?: boolean;
    /**
     * The instance type for a dedicated master node.
     * @type {string}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    DedicatedMasterType?: string;
    /**
     * The number of instances in the specified domain cluster.
     * @type {number}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    InstanceCount?: number;
    /**
     * The instance type for an Elasticsearch cluster. UltraWarm instance types are not supported for data instances.
     * @type {string}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    InstanceType?: string;
    /**
     * The number of warm nodes in the cluster.
     * @type {number}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    WarmCount?: number;
    /**
     * True to enable warm storage.
     * @type {boolean}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    WarmEnabled?: boolean;
    /**
     * The instance type for the Elasticsearch cluster\'s warm nodes.
     * @type {string}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    WarmType?: string;
    /**
     * 
     * @type {ElasticsearchserviceZoneAwarenessConfig}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    ZoneAwarenessConfig?: ElasticsearchserviceZoneAwarenessConfig;
    /**
     * A boolean value to indicate whether zone awareness is enabled. See About Zone Awareness (http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-zoneawareness) for more information.
     * @type {boolean}
     * @memberof ElasticsearchserviceElasticsearchClusterConfig
     */
    ZoneAwarenessEnabled?: boolean;
}


