/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceElasticsearchVersionStatus
 */
export interface ElasticsearchserviceElasticsearchVersionStatus {
    /**
     * Specifies the Elasticsearch version for the specified Elasticsearch domain.  Options is a required field
     * @type {string}
     * @memberof ElasticsearchserviceElasticsearchVersionStatus
     */
    Options?: string;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceElasticsearchVersionStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


