/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceServiceSoftwareOptions
 */
export interface ElasticsearchserviceServiceSoftwareOptions {
    /**
     * Timestamp, in Epoch time, until which you can manually request a service software update. After this date, we automatically update your service software.
     * @type {string}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    AutomatedUpdateDate?: string;
    /**
     * True if you are able to cancel your service software version update. False if you are not able to cancel your service software version.
     * @type {boolean}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    Cancellable?: boolean;
    /**
     * The current service software version that is present on the domain.
     * @type {string}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    CurrentVersion?: string;
    /**
     * The description of the UpdateStatus.
     * @type {string}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    Description?: string;
    /**
     * The new service software version if one is available.
     * @type {string}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    NewVersion?: string;
    /**
     * True if a service software is never automatically updated. False if a service software is automatically updated after AutomatedUpdateDate.
     * @type {boolean}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    OptionalDeployment?: boolean;
    /**
     * True if you are able to update you service software version. False if you are not able to update your service software version.
     * @type {boolean}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    UpdateAvailable?: boolean;
    /**
     * The status of your service software update. This field can take the following values: ELIGIBLE, PENDING_UPDATE, IN_PROGRESS, COMPLETED, and NOT_ELIGIBLE.
     * @type {string}
     * @memberof ElasticsearchserviceServiceSoftwareOptions
     */
    UpdateStatus?: string;
}


