/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceAutoTuneMaintenanceSchedule } from './elasticsearchservice-auto-tune-maintenance-schedule';

/**
 * 
 * @export
 * @interface ElasticsearchserviceAutoTuneOptions
 */
export interface ElasticsearchserviceAutoTuneOptions {
    /**
     * Specifies the Auto-Tune desired state. Valid values are ENABLED, DISABLED.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneOptions
     */
    DesiredState?: string;
    /**
     * Specifies list of maitenance schedules. See the Developer Guide (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/auto-tune.html) for more information.
     * @type {Array<ElasticsearchserviceAutoTuneMaintenanceSchedule>}
     * @memberof ElasticsearchserviceAutoTuneOptions
     */
    MaintenanceSchedules?: Array<ElasticsearchserviceAutoTuneMaintenanceSchedule>;
    /**
     * Specifies the rollback state while disabling Auto-Tune for the domain. Valid values are NO_ROLLBACK, DEFAULT_ROLLBACK.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneOptions
     */
    RollbackOnDisable?: string;
}


