/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticacheDestinationDetails } from './elasticache-destination-details';

/**
 * 
 * @export
 * @interface ElasticacheLogDeliveryConfiguration
 */
export interface ElasticacheLogDeliveryConfiguration {
    /**
     * 
     * @type {ElasticacheDestinationDetails}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    destinationDetails?: ElasticacheDestinationDetails;
    /**
     * Returns the destination type, either cloudwatch-logs or kinesis-firehose.
     * @type {string}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    destinationType?: string;
    /**
     * Returns the log format, either JSON or TEXT.
     * @type {string}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    logFormat?: string;
    /**
     * Refers to slow-log (https://redis.io/commands/slowlog).
     * @type {string}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    logType?: string;
    /**
     * Returns an error message for the log delivery configuration.
     * @type {string}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    message?: string;
    /**
     * Returns the log delivery configuration status. Values are one of enabling | disabling | modifying | active | error
     * @type {string}
     * @memberof ElasticacheLogDeliveryConfiguration
     */
    status?: string;
}


