/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceVPCDerivedInfo
 */
export interface ElasticsearchserviceVPCDerivedInfo {
    /**
     * The availability zones for the Elasticsearch domain. Exists only if the domain was created with VPCOptions.
     * @type {Array<string>}
     * @memberof ElasticsearchserviceVPCDerivedInfo
     */
    AvailabilityZones?: Array<string>;
    /**
     * Specifies the security groups for VPC endpoint.
     * @type {Array<string>}
     * @memberof ElasticsearchserviceVPCDerivedInfo
     */
    SecurityGroupIds?: Array<string>;
    /**
     * Specifies the subnets for VPC endpoint.
     * @type {Array<string>}
     * @memberof ElasticsearchserviceVPCDerivedInfo
     */
    SubnetIds?: Array<string>;
    /**
     * The VPC Id for the Elasticsearch domain. Exists only if the domain was created with VPCOptions.
     * @type {string}
     * @memberof ElasticsearchserviceVPCDerivedInfo
     */
    VPCId?: string;
}


