/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceAutoTuneOptionsOutput
 */
export interface ElasticsearchserviceAutoTuneOptionsOutput {
    /**
     * Specifies the error message while enabling or disabling the Auto-Tune.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneOptionsOutput
     */
    ErrorMessage?: string;
    /**
     * Specifies the AutoTuneState for the Elasticsearch domain.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneOptionsOutput
     */
    State?: string;
}


