/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticacheCloudWatchLogsDestinationDetails
 */
export interface ElasticacheCloudWatchLogsDestinationDetails {
    /**
     * The name of the CloudWatch Logs log group.
     * @type {string}
     * @memberof ElasticacheCloudWatchLogsDestinationDetails
     */
    logGroup?: string;
}


