/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticacheTag } from './elasticache-tag';

/**
 * 
 * @export
 * @interface ElasticacheTagListMessage
 */
export interface ElasticacheTagListMessage {
    /**
     * A list of tags as key-value pairs.
     * @type {Array<ElasticacheTag>}
     * @memberof ElasticacheTagListMessage
     */
    TagList?: Array<ElasticacheTag>;
}


