/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceLogPublishingOption } from './elasticsearchservice-log-publishing-option';
import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceLogPublishingOptionsStatus
 */
export interface ElasticsearchserviceLogPublishingOptionsStatus {
    /**
     * The log publishing options configured for the Elasticsearch domain.
     * @type {{ [key: string]: ElasticsearchserviceLogPublishingOption; }}
     * @memberof ElasticsearchserviceLogPublishingOptionsStatus
     */
    Options?: { [key: string]: ElasticsearchserviceLogPublishingOption; };
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceLogPublishingOptionsStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


