/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceDuration } from './elasticsearchservice-duration';

/**
 * 
 * @export
 * @interface ElasticsearchserviceAutoTuneMaintenanceSchedule
 */
export interface ElasticsearchserviceAutoTuneMaintenanceSchedule {
    /**
     * Specifies cron expression for a recurring maintenance schedule. See the Developer Guide (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/auto-tune.html) for more information.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneMaintenanceSchedule
     */
    CronExpressionForRecurrence?: string;
    /**
     * 
     * @type {ElasticsearchserviceDuration}
     * @memberof ElasticsearchserviceAutoTuneMaintenanceSchedule
     */
    Duration?: ElasticsearchserviceDuration;
    /**
     * Specifies timestamp at which Auto-Tune maintenance schedule start.
     * @type {string}
     * @memberof ElasticsearchserviceAutoTuneMaintenanceSchedule
     */
    StartAt?: string;
}


