/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceAdvancedOptionsStatus
 */
export interface ElasticsearchserviceAdvancedOptionsStatus {
    /**
     * Specifies the status of advanced options for the specified Elasticsearch domain.  Options is a required field
     * @type {{ [key: string]: string; }}
     * @memberof ElasticsearchserviceAdvancedOptionsStatus
     */
    Options?: { [key: string]: string; };
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceAdvancedOptionsStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


