/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceTag } from './elasticsearchservice-tag';

/**
 * 
 * @export
 * @interface ElasticsearchserviceListTagsOutput
 */
export interface ElasticsearchserviceListTagsOutput {
    /**
     * List of Tag for the requested Elasticsearch domain.
     * @type {Array<ElasticsearchserviceTag>}
     * @memberof ElasticsearchserviceListTagsOutput
     */
    TagList?: Array<ElasticsearchserviceTag>;
}


