/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ElasticsearchserviceEBSOptions
 */
export interface ElasticsearchserviceEBSOptions {
    /**
     * Specifies whether EBS-based storage is enabled.
     * @type {boolean}
     * @memberof ElasticsearchserviceEBSOptions
     */
    EBSEnabled?: boolean;
    /**
     * Specifies the IOPD for a Provisioned IOPS EBS volume (SSD).
     * @type {number}
     * @memberof ElasticsearchserviceEBSOptions
     */
    Iops?: number;
    /**
     * Integer to specify the size of an EBS volume.
     * @type {number}
     * @memberof ElasticsearchserviceEBSOptions
     */
    VolumeSize?: number;
    /**
     * Specifies the volume type for EBS-based storage.
     * @type {string}
     * @memberof ElasticsearchserviceEBSOptions
     */
    VolumeType?: string;
}


