/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ElasticsearchserviceEBSOptions } from './elasticsearchservice-ebsoptions';
import { ElasticsearchserviceOptionStatus } from './elasticsearchservice-option-status';

/**
 * 
 * @export
 * @interface ElasticsearchserviceEBSOptionsStatus
 */
export interface ElasticsearchserviceEBSOptionsStatus {
    /**
     * 
     * @type {ElasticsearchserviceEBSOptions}
     * @memberof ElasticsearchserviceEBSOptionsStatus
     */
    Options?: ElasticsearchserviceEBSOptions;
    /**
     * 
     * @type {ElasticsearchserviceOptionStatus}
     * @memberof ElasticsearchserviceEBSOptionsStatus
     */
    Status?: ElasticsearchserviceOptionStatus;
}


