/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface IntegrationsKubeIntegration
 */
export interface IntegrationsKubeIntegration {
    /**
     * 
     * @type {string}
     * @memberof IntegrationsKubeIntegration
     */
    CreatedAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof IntegrationsKubeIntegration
     */
    DeletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsKubeIntegration
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsKubeIntegration
     */
    UpdatedAt?: string;
    /**
     * Certificate data is used by x509 auth mechanisms over TLS
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    client_certificate_data?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    client_key_data?: Array<number>;
    /**
     * The raw kubeconfig, used by local auth mechanisms
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    kubeconfig?: Array<number>;
    /**
     * The name of the auth mechanism
     * @type {string}
     * @memberof IntegrationsKubeIntegration
     */
    mechanism?: string;
    /**
     * The Organization that this integration belongs to
     * @type {number}
     * @memberof IntegrationsKubeIntegration
     */
    organization_id?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    password?: Array<number>;
    /**
     * Token is used for bearer-token auth mechanisms
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    token?: Array<number>;
    /**
     * The id of the user that linked this auth mechanism
     * @type {number}
     * @memberof IntegrationsKubeIntegration
     */
    user_id?: number;
    /**
     * Username/Password for basic authentication to a cluster
     * @type {Array<number>}
     * @memberof IntegrationsKubeIntegration
     */
    username?: Array<number>;
}


