/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface IntegrationsOAuthIntegration
 */
export interface IntegrationsOAuthIntegration {
    /**
     * 
     * @type {string}
     * @memberof IntegrationsOAuthIntegration
     */
    CreatedAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof IntegrationsOAuthIntegration
     */
    DeletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof IntegrationsOAuthIntegration
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsOAuthIntegration
     */
    UpdatedAt?: string;
    /**
     * The end-users\'s access token
     * @type {Array<number>}
     * @memberof IntegrationsOAuthIntegration
     */
    access_token?: Array<number>;
    /**
     * The name of the auth mechanism
     * @type {string}
     * @memberof IntegrationsOAuthIntegration
     */
    client?: string;
    /**
     * The ID issued to the client
     * @type {Array<number>}
     * @memberof IntegrationsOAuthIntegration
     */
    client_id?: Array<number>;
    /**
     * The Organization that this integration belongs to
     * @type {number}
     * @memberof IntegrationsOAuthIntegration
     */
    organization_id?: number;
    /**
     * The end-user\'s refresh token
     * @type {Array<number>}
     * @memberof IntegrationsOAuthIntegration
     */
    refresh_token?: Array<number>;
    /**
     * The id of the user that linked this auth mechanism
     * @type {number}
     * @memberof IntegrationsOAuthIntegration
     */
    user_id?: number;
}


