/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { S3Bucket } from './s3-bucket';
import { S3Owner } from './s3-owner';

/**
 * 
 * @export
 * @interface IntegrationsBucketsInRegion
 */
export interface IntegrationsBucketsInRegion {
    /**
     * The list of buckets owned by the requestor.
     * @type {Array<S3Bucket>}
     * @memberof IntegrationsBucketsInRegion
     */
    Buckets?: Array<S3Bucket>;
    /**
     * 
     * @type {S3Owner}
     * @memberof IntegrationsBucketsInRegion
     */
    Owner?: S3Owner;
    /**
     * 
     * @type {string}
     * @memberof IntegrationsBucketsInRegion
     */
    Region?: string;
}


