/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IntegrationsBucketsInRegion } from './integrations-buckets-in-region';
import { IntegrationsDescribeClusterOutput } from './integrations-describe-cluster-output';
import { IntegrationsDescribeDBInstancesOutput } from './integrations-describe-dbinstances-output';
import { IntegrationsDescribeElasticacheCluster } from './integrations-describe-elasticache-cluster';

/**
 * 
 * @export
 * @interface IntegrationsAwsResources
 */
export interface IntegrationsAwsResources {
    /**
     * 
     * @type {Array<IntegrationsDescribeClusterOutput>}
     * @memberof IntegrationsAwsResources
     */
    clusters?: Array<IntegrationsDescribeClusterOutput>;
    /**
     * 
     * @type {Array<IntegrationsDescribeElasticacheCluster>}
     * @memberof IntegrationsAwsResources
     */
    elasticache?: Array<IntegrationsDescribeElasticacheCluster>;
    /**
     * 
     * @type {Array<IntegrationsDescribeDBInstancesOutput>}
     * @memberof IntegrationsAwsResources
     */
    rds?: Array<IntegrationsDescribeDBInstancesOutput>;
    /**
     * 
     * @type {Array<IntegrationsBucketsInRegion>}
     * @memberof IntegrationsAwsResources
     */
    s3_buckets?: Array<IntegrationsBucketsInRegion>;
}


