/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KubernetesListResourceInYamlOutput
 */
export interface KubernetesListResourceInYamlOutput {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    Certificate?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    ConfigMap?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    Ingress?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    Pod?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    Secrets?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof KubernetesListResourceInYamlOutput
     */
    Service?: { [key: string]: string; };
}


