/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';
import { ModelsOrganization } from './models-organization';

/**
 * 
 * @export
 * @interface ModelsEnvironment
 */
export interface ModelsEnvironment {
    /**
     * 
     * @type {string}
     * @memberof ModelsEnvironment
     */
    CreatedAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsEnvironment
     */
    DeletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsEnvironment
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsEnvironment
     */
    UpdatedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsEnvironment
     */
    isSetup?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsEnvironment
     */
    name?: string;
    /**
     * 
     * @type {ModelsOrganization}
     * @memberof ModelsEnvironment
     */
    organization?: ModelsOrganization;
    /**
     * 
     * @type {number}
     * @memberof ModelsEnvironment
     */
    organization_id?: number;
    /**
     * region this environment belongs to
     * @type {string}
     * @memberof ModelsEnvironment
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsEnvironment
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsEnvironment
     */
    tf_configs?: string;
    /**
     * uid for this environment
     * @type {string}
     * @memberof ModelsEnvironment
     */
    uid?: string;
    /**
     * virtual private cloud
     * @type {string}
     * @memberof ModelsEnvironment
     */
    vpc?: string;
}


