/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface ModelsCapsule
 */
export interface ModelsCapsule {
    /**
     * 
     * @type {string}
     * @memberof ModelsCapsule
     */
    CreatedAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsCapsule
     */
    DeletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsCapsule
     */
    ID?: number;
    /**
     * A random 6-byte suffix to ensure workspace/stream ids are unique
     * @type {string}
     * @memberof ModelsCapsule
     */
    Suffix?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCapsule
     */
    UpdatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCapsule
     */
    capsule_id?: number;
    /**
     * The type of capsule that was provisioned this could be a capsule or app capsule
     * @type {string}
     * @memberof ModelsCapsule
     */
    kind?: string;
    /**
     * The date of last applied
     * @type {string}
     * @memberof ModelsCapsule
     */
    last_applied_at?: string;
    /**
     * The last-applied config file
     * @type {string}
     * @memberof ModelsCapsule
     */
    last_applied_config?: string;
    /**
     * The Organization that this capsule belongs to
     * @type {number}
     * @memberof ModelsCapsule
     */
    organization_id?: number;
    /**
     * Status is the status of the capsule
     * @type {string}
     * @memberof ModelsCapsule
     */
    status?: string;
    /**
     * id only allows you to have uuid field, use uid field, with a unique constraint
     * @type {string}
     * @memberof ModelsCapsule
     */
    uid?: string;
}


