/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface ModelsJob
 */
export interface ModelsJob {
    /**
     * 
     * @type {string}
     * @memberof ModelsJob
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsJob
     */
    deletedAt?: GormDeletedAt;
    /**
     * an environment may have many jobs
     * @type {number}
     * @memberof ModelsJob
     */
    environment_id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsJob
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsJob
     */
    job_type?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsJob
     */
    organization_id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsJob
     */
    resource_type?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsJob
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsJob
     */
    updatedAt?: string;
}


