/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GormDeletedAt } from './gorm-deleted-at';

/**
 * 
 * @export
 * @interface ModelsGhInstallation
 */
export interface ModelsGhInstallation {
    /**
     * 
     * @type {number}
     * @memberof ModelsGhInstallation
     */
    accountID?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsGhInstallation
     */
    accountOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGhInstallation
     */
    createdAt?: string;
    /**
     * 
     * @type {GormDeletedAt}
     * @memberof ModelsGhInstallation
     */
    deletedAt?: GormDeletedAt;
    /**
     * 
     * @type {number}
     * @memberof ModelsGhInstallation
     */
    id?: number;
    /**
     * The organization that this integration belongs to
     * @type {number}
     * @memberof ModelsGhInstallation
     */
    organizationID?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsGhInstallation
     */
    targetType?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGhInstallation
     */
    updatedAt?: string;
}


