/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsDBInstanceStatusInfo
 */
export interface RdsDBInstanceStatusInfo {
    /**
     * Details of the error if there is an error for the instance. If the instance isn\'t in an error state, this value is blank.
     * @type {string}
     * @memberof RdsDBInstanceStatusInfo
     */
    message?: string;
    /**
     * Boolean value that is true if the instance is operating normally, or false if the instance is in an error state.
     * @type {boolean}
     * @memberof RdsDBInstanceStatusInfo
     */
    normal?: boolean;
    /**
     * Status of the DB instance. For a StatusType of read replica, the values can be replicating, replication stop point set, replication stop point reached, error, stopped, or terminated.
     * @type {string}
     * @memberof RdsDBInstanceStatusInfo
     */
    status?: string;
    /**
     * This value is currently \"read replication.\"
     * @type {string}
     * @memberof RdsDBInstanceStatusInfo
     */
    statusType?: string;
}


