/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsEndpoint
 */
export interface RdsEndpoint {
    /**
     * Specifies the DNS address of the DB instance.
     * @type {string}
     * @memberof RdsEndpoint
     */
    Address?: string;
    /**
     * Specifies the ID that Amazon Route 53 assigns when you create a hosted zone.
     * @type {string}
     * @memberof RdsEndpoint
     */
    HostedZoneId?: string;
    /**
     * Specifies the port that the database engine is listening on.
     * @type {number}
     * @memberof RdsEndpoint
     */
    Port?: number;
}


