/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsDomainMembership
 */
export interface RdsDomainMembership {
    /**
     * The identifier of the Active Directory Domain.
     * @type {string}
     * @memberof RdsDomainMembership
     */
    Domain?: string;
    /**
     * The fully qualified domain name of the Active Directory Domain.
     * @type {string}
     * @memberof RdsDomainMembership
     */
    FQDN?: string;
    /**
     * The name of the IAM role to be used when making API calls to the Directory Service.
     * @type {string}
     * @memberof RdsDomainMembership
     */
    IAMRoleName?: string;
    /**
     * The status of the Active Directory Domain membership for the DB instance or cluster. Values include joined, pending-join, failed, and so on.
     * @type {string}
     * @memberof RdsDomainMembership
     */
    Status?: string;
}


