/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsDBSecurityGroupMembership
 */
export interface RdsDBSecurityGroupMembership {
    /**
     * The name of the DB security group.
     * @type {string}
     * @memberof RdsDBSecurityGroupMembership
     */
    DBSecurityGroupName?: string;
    /**
     * The status of the DB security group.
     * @type {string}
     * @memberof RdsDBSecurityGroupMembership
     */
    Status?: string;
}


