/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsVpcSecurityGroupMembership
 */
export interface RdsVpcSecurityGroupMembership {
    /**
     * The status of the VPC security group.
     * @type {string}
     * @memberof RdsVpcSecurityGroupMembership
     */
    status?: string;
    /**
     * The name of the VPC security group.
     * @type {string}
     * @memberof RdsVpcSecurityGroupMembership
     */
    vpcSecurityGroupId?: string;
}


