/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RdsPendingCloudwatchLogsExports
 */
export interface RdsPendingCloudwatchLogsExports {
    /**
     * Log types that are in the process of being enabled. After they are enabled, these log types are exported to CloudWatch Logs.
     * @type {Array<string>}
     * @memberof RdsPendingCloudwatchLogsExports
     */
    logTypesToDisable?: Array<string>;
    /**
     * Log types that are in the process of being deactivated. After they are deactivated, these log types aren\'t exported to CloudWatch Logs.
     * @type {Array<string>}
     * @memberof RdsPendingCloudwatchLogsExports
     */
    logTypesToEnable?: Array<string>;
}


