/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RdsPendingCloudwatchLogsExports } from './rds-pending-cloudwatch-logs-exports';
import { RdsProcessorFeature } from './rds-processor-feature';

/**
 * 
 * @export
 * @interface RdsPendingModifiedValues
 */
export interface RdsPendingModifiedValues {
    /**
     * The allocated storage size for the DB instance specified in gibibytes .
     * @type {number}
     * @memberof RdsPendingModifiedValues
     */
    AllocatedStorage?: number;
    /**
     * The number of days for which automated backups are retained.
     * @type {number}
     * @memberof RdsPendingModifiedValues
     */
    BackupRetentionPeriod?: number;
    /**
     * The identifier of the CA certificate for the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    CACertificateIdentifier?: string;
    /**
     * The name of the compute and memory capacity class for the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    DBInstanceClass?: string;
    /**
     * The database identifier for the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    DBInstanceIdentifier?: string;
    /**
     * The DB subnet group for the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    DBSubnetGroupName?: string;
    /**
     * The database engine version.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    EngineVersion?: string;
    /**
     * Whether mapping of AWS Identity and Access Management (IAM) accounts to database accounts is enabled.
     * @type {boolean}
     * @memberof RdsPendingModifiedValues
     */
    IAMDatabaseAuthenticationEnabled?: boolean;
    /**
     * The Provisioned IOPS value for the DB instance.
     * @type {number}
     * @memberof RdsPendingModifiedValues
     */
    Iops?: number;
    /**
     * The license model for the DB instance.  Valid values: license-included | bring-your-own-license | general-public-license
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    LicenseModel?: string;
    /**
     * The master credentials for the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    MasterUserPassword?: string;
    /**
     * A value that indicates that the Single-AZ DB instance will change to a Multi-AZ deployment.
     * @type {boolean}
     * @memberof RdsPendingModifiedValues
     */
    MultiAZ?: boolean;
    /**
     * 
     * @type {RdsPendingCloudwatchLogsExports}
     * @memberof RdsPendingModifiedValues
     */
    PendingCloudwatchLogsExports?: RdsPendingCloudwatchLogsExports;
    /**
     * The port for the DB instance.
     * @type {number}
     * @memberof RdsPendingModifiedValues
     */
    Port?: number;
    /**
     * The number of CPU cores and the number of threads per core for the DB instance class of the DB instance.
     * @type {Array<RdsProcessorFeature>}
     * @memberof RdsPendingModifiedValues
     */
    ProcessorFeatures?: Array<RdsProcessorFeature>;
    /**
     * The storage type of the DB instance.
     * @type {string}
     * @memberof RdsPendingModifiedValues
     */
    StorageType?: string;
}


