/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RdsSubnet } from './rds-subnet';

/**
 * 
 * @export
 * @interface RdsDBSubnetGroup
 */
export interface RdsDBSubnetGroup {
    /**
     * The Amazon Resource Name (ARN) for the DB subnet group.
     * @type {string}
     * @memberof RdsDBSubnetGroup
     */
    dbsubnetGroupArn?: string;
    /**
     * Provides the description of the DB subnet group.
     * @type {string}
     * @memberof RdsDBSubnetGroup
     */
    dbsubnetGroupDescription?: string;
    /**
     * The name of the DB subnet group.
     * @type {string}
     * @memberof RdsDBSubnetGroup
     */
    dbsubnetGroupName?: string;
    /**
     * Provides the status of the DB subnet group.
     * @type {string}
     * @memberof RdsDBSubnetGroup
     */
    subnetGroupStatus?: string;
    /**
     * Contains a list of Subnet elements.
     * @type {Array<RdsSubnet>}
     * @memberof RdsDBSubnetGroup
     */
    subnets?: Array<RdsSubnet>;
    /**
     * Provides the VpcId of the DB subnet group.
     * @type {string}
     * @memberof RdsDBSubnetGroup
     */
    vpcId?: string;
}


