/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RdsDBInstance } from './rds-dbinstance';

/**
 * 
 * @export
 * @interface RdsDescribeDBInstancesOutput
 */
export interface RdsDescribeDBInstancesOutput {
    /**
     * A list of DBInstance instances.
     * @type {Array<RdsDBInstance>}
     * @memberof RdsDescribeDBInstancesOutput
     */
    DBInstances?: Array<RdsDBInstance>;
    /**
     * An optional pagination token provided by a previous request. If this parameter is specified, the response includes only records beyond the marker, up to the value specified by MaxRecords .
     * @type {string}
     * @memberof RdsDescribeDBInstancesOutput
     */
    Marker?: string;
}


