/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface S3Owner
 */
export interface S3Owner {
    /**
     * Container for the display name of the owner.
     * @type {string}
     * @memberof S3Owner
     */
    DisplayName?: string;
    /**
     * Container for the ID of the owner.
     * @type {string}
     * @memberof S3Owner
     */
    ID?: string;
}


