/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypesAppDeployRequest
 */
export interface TypesAppDeployRequest {
    /**
     * EnvironmentID int    `json:\"environment_id\" yaml:\"environment_id\"`
     * @type {boolean}
     * @memberof TypesAppDeployRequest
     */
    dry_run?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof TypesAppDeployRequest
     */
    setOptions?: Array<string>;
    /**
     * values yaml encode in base64
     * @type {string}
     * @memberof TypesAppDeployRequest
     */
    values?: string;
}


