/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TypesAppDeleteRequest } from './types-app-delete-request';

/**
 * 
 * @export
 * @interface TypesToolDeleteRequest
 */
export interface TypesToolDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof TypesToolDeleteRequest
     */
    kind?: string;
    /**
     * 
     * @type {Array<TypesAppDeleteRequest>}
     * @memberof TypesToolDeleteRequest
     */
    spec?: Array<TypesAppDeleteRequest>;
    /**
     * 
     * @type {string}
     * @memberof TypesToolDeleteRequest
     */
    version?: string;
}


