/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypesAppDeleteResponse
 */
export interface TypesAppDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    app_name?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    cluster_name?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    cluster_region?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    environment?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesAppDeleteResponse
     */
    status?: string;
}


