/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TypesNodeGroup } from './types-node-group';

/**
 * 
 * @export
 * @interface TypesCluster
 */
export interface TypesCluster {
    /**
     * Name of the cluster limit the cluster to 32 chars in length
     * @type {string}
     * @memberof TypesCluster
     */
    name?: string;
    /**
     * 
     * @type {TypesNodeGroup}
     * @memberof TypesCluster
     */
    node_group?: TypesNodeGroup;
    /**
     * the region this cluster belongs to @todo make this enum
     * @type {string}
     * @memberof TypesCluster
     */
    region?: string;
}


