/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypesNodeGroup
 */
export interface TypesNodeGroup {
    /**
     * 
     * @type {number}
     * @memberof TypesNodeGroup
     */
    disk_size?: number;
    /**
     * Instance type @todo provide enum values for this
     * @type {string}
     * @memberof TypesNodeGroup
     */
    instance_type?: string;
    /**
     * name of the environment
     * @type {string}
     * @memberof TypesNodeGroup
     */
    name?: string;
    /**
     * the namespace this node group belongs to
     * @type {string}
     * @memberof TypesNodeGroup
     */
    namespace?: string;
    /**
     * current number of instance running max val 4,294,967,295
     * @type {number}
     * @memberof TypesNodeGroup
     */
    number_of_instance?: number;
    /**
     * max number of instances running
     * @type {number}
     * @memberof TypesNodeGroup
     */
    number_of_instance_max?: number;
    /**
     * min number of instances running
     * @type {number}
     * @memberof TypesNodeGroup
     */
    number_of_instance_min?: number;
    /**
     * is the environment using spot
     * @type {boolean}
     * @memberof TypesNodeGroup
     */
    spot?: boolean;
}


