/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ArgoWorkflowsDescriptionStruct
 */
export interface V1ArgoWorkflowsDescriptionStruct {
    /**
     * 
     * @type {string}
     * @memberof V1ArgoWorkflowsDescriptionStruct
     */
    example?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ArgoWorkflowsDescriptionStruct
     */
    _long?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ArgoWorkflowsDescriptionStruct
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ArgoWorkflowsDescriptionStruct
     */
    _short?: string;
}


