/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1AwsS3StaticSite
 */
export interface V1AwsS3StaticSite {
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    error_document?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    index_document?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    log_bucket_name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    visibility?: string;
    /**
     * 
     * @type {string}
     * @memberof V1AwsS3StaticSite
     */
    website?: string;
}


