/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CapsulesInputCertManager } from './capsules-input-cert-manager';
import { CapsulesInputClusterAutoScaler } from './capsules-input-cluster-auto-scaler';
import { CapsulesInputClusterIssuer } from './capsules-input-cluster-issuer';
import { CapsulesInputCustomApp } from './capsules-input-custom-app';
import { CapsulesInputElk } from './capsules-input-elk';
import { CapsulesInputEventExporter } from './capsules-input-event-exporter';
import { CapsulesInputFluentBit } from './capsules-input-fluent-bit';
import { CapsulesInputGrafana } from './capsules-input-grafana';
import { CapsulesInputPrometheus } from './capsules-input-prometheus';

/**
 * 
 * @export
 * @interface V1CapsulesStruct
 */
export interface V1CapsulesStruct {
    /**
     * 
     * @type {CapsulesInputCertManager}
     * @memberof V1CapsulesStruct
     */
    cert_manager?: CapsulesInputCertManager;
    /**
     * Clickhouse expects the values.yaml file to be passed as a parameter the parameter must be a json converted converted file  refer to the charts repo for the values.yaml file
     * @type {object}
     * @memberof V1CapsulesStruct
     */
    clickhouse?: object;
    /**
     * 
     * @type {CapsulesInputClusterAutoScaler}
     * @memberof V1CapsulesStruct
     */
    clusterAutoScaler?: CapsulesInputClusterAutoScaler;
    /**
     * 
     * @type {CapsulesInputClusterIssuer}
     * @memberof V1CapsulesStruct
     */
    clusterIssuer?: CapsulesInputClusterIssuer;
    /**
     * 
     * @type {CapsulesInputCustomApp}
     * @memberof V1CapsulesStruct
     */
    custom?: CapsulesInputCustomApp;
    /**
     * 
     * @type {CapsulesInputElk}
     * @memberof V1CapsulesStruct
     */
    elk?: CapsulesInputElk;
    /**
     * 
     * @type {CapsulesInputEventExporter}
     * @memberof V1CapsulesStruct
     */
    eventExporter?: CapsulesInputEventExporter;
    /**
     * 
     * @type {CapsulesInputFluentBit}
     * @memberof V1CapsulesStruct
     */
    fluentBit?: CapsulesInputFluentBit;
    /**
     * 
     * @type {CapsulesInputGrafana}
     * @memberof V1CapsulesStruct
     */
    grafana?: CapsulesInputGrafana;
    /**
     * 
     * @type {CapsulesInputPrometheus}
     * @memberof V1CapsulesStruct
     */
    prometheus?: CapsulesInputPrometheus;
}


