/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ContainerStateRunning } from './v1-container-state-running';
import { V1ContainerStateTerminated } from './v1-container-state-terminated';
import { V1ContainerStateWaiting } from './v1-container-state-waiting';

/**
 * 
 * @export
 * @interface V1ContainerState
 */
export interface V1ContainerState {
    /**
     * 
     * @type {V1ContainerStateRunning}
     * @memberof V1ContainerState
     */
    running?: V1ContainerStateRunning;
    /**
     * 
     * @type {V1ContainerStateTerminated}
     * @memberof V1ContainerState
     */
    terminated?: V1ContainerStateTerminated;
    /**
     * 
     * @type {V1ContainerStateWaiting}
     * @memberof V1ContainerState
     */
    waiting?: V1ContainerStateWaiting;
}


