/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Capabilities
 */
export interface V1Capabilities {
    /**
     * Added capabilities +optional
     * @type {Array<string>}
     * @memberof V1Capabilities
     */
    add?: Array<string>;
    /**
     * Removed capabilities +optional
     * @type {Array<string>}
     * @memberof V1Capabilities
     */
    drop?: Array<string>;
}


