/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1DownwardAPIVolumeFile } from './v1-downward-apivolume-file';

/**
 * 
 * @export
 * @interface V1DownwardAPIProjection
 */
export interface V1DownwardAPIProjection {
    /**
     * Items is a list of DownwardAPIVolume file +optional
     * @type {Array<V1DownwardAPIVolumeFile>}
     * @memberof V1DownwardAPIProjection
     */
    items?: Array<V1DownwardAPIVolumeFile>;
}


