/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1DaemonSetStruct
 */
export interface V1DaemonSetStruct {
    /**
     * 
     * @type {number}
     * @memberof V1DaemonSetStruct
     */
    CreatedAt?: number;
    /**
     * 
     * @type {string}
     * @memberof V1DaemonSetStruct
     */
    Manifest?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DaemonSetStruct
     */
    Name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DaemonSetStruct
     */
    Namespace?: string;
    /**
     * 
     * @type {number}
     * @memberof V1DaemonSetStruct
     */
    PodsDesired?: number;
    /**
     * 
     * @type {number}
     * @memberof V1DaemonSetStruct
     */
    PodsReady?: number;
    /**
     * 
     * @type {string}
     * @memberof V1DaemonSetStruct
     */
    StrategyType?: string;
}


