/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Elasticsearch
 */
export interface V1Elasticsearch {
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    advanced_security_options_enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    advanced_security_options_internal_user_database_enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    advanced_security_options_master_user_name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    advanced_security_options_master_user_password?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Elasticsearch
     */
    az_count?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    create_iam_service_linked_role?: boolean;
    /**
     * 
     * @type {number}
     * @memberof V1Elasticsearch
     */
    dedicated_master_count?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    dedicated_master_enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    dedicated_master_type?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    dns_zone_id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    domain_hostname_enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof V1Elasticsearch
     */
    ebs_volume_size?: number;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    elasticsearch_subdomain_name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    elasticsearch_version?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Elasticsearch
     */
    instance_count_per_az?: number;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    instance_type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    is_public?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V1Elasticsearch
     */
    kibana_hostname_enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    kibana_subdomain_name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Elasticsearch
     */
    name?: string;
}


