/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ConfigMapKeySelector } from './v1-config-map-key-selector';
import { V1ObjectFieldSelector } from './v1-object-field-selector';
import { V1ResourceFieldSelector } from './v1-resource-field-selector';
import { V1SecretKeySelector } from './v1-secret-key-selector';

/**
 * 
 * @export
 * @interface V1EnvVarSource
 */
export interface V1EnvVarSource {
    /**
     * 
     * @type {V1ConfigMapKeySelector}
     * @memberof V1EnvVarSource
     */
    configMapKeyRef?: V1ConfigMapKeySelector;
    /**
     * 
     * @type {V1ObjectFieldSelector}
     * @memberof V1EnvVarSource
     */
    fieldRef?: V1ObjectFieldSelector;
    /**
     * 
     * @type {V1ResourceFieldSelector}
     * @memberof V1EnvVarSource
     */
    resourceFieldRef?: V1ResourceFieldSelector;
    /**
     * 
     * @type {V1SecretKeySelector}
     * @memberof V1EnvVarSource
     */
    secretKeyRef?: V1SecretKeySelector;
}


