/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1PersistentVolumeClaimTemplate } from './v1-persistent-volume-claim-template';

/**
 * 
 * @export
 * @interface V1EphemeralVolumeSource
 */
export interface V1EphemeralVolumeSource {
    /**
     * 
     * @type {V1PersistentVolumeClaimTemplate}
     * @memberof V1EphemeralVolumeSource
     */
    volumeClaimTemplate?: V1PersistentVolumeClaimTemplate;
}


