/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ConfigMapEnvSource } from './v1-config-map-env-source';
import { V1SecretEnvSource } from './v1-secret-env-source';

/**
 * 
 * @export
 * @interface V1EnvFromSource
 */
export interface V1EnvFromSource {
    /**
     * 
     * @type {V1ConfigMapEnvSource}
     * @memberof V1EnvFromSource
     */
    configMapRef?: V1ConfigMapEnvSource;
    /**
     * An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER. +optional
     * @type {string}
     * @memberof V1EnvFromSource
     */
    prefix?: string;
    /**
     * 
     * @type {V1SecretEnvSource}
     * @memberof V1EnvFromSource
     */
    secretRef?: V1SecretEnvSource;
}


