/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1GetApplicationDetailsHasuraRequestInput } from './v1-get-application-details-hasura-request-input';

/**
 * 
 * @export
 * @interface V1GetApplicationDetailsHasuraRequest
 */
export interface V1GetApplicationDetailsHasuraRequest {
    /**
     * 
     * @type {V1GetApplicationDetailsHasuraRequestInput}
     * @memberof V1GetApplicationDetailsHasuraRequest
     */
    input?: V1GetApplicationDetailsHasuraRequestInput;
}


