/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1GetApplicationDetailsHasuraRequestInputArg } from './v1-get-application-details-hasura-request-input-arg';

/**
 * 
 * @export
 * @interface V1GetApplicationDetailsHasuraRequestInput
 */
export interface V1GetApplicationDetailsHasuraRequestInput {
    /**
     * 
     * @type {V1GetApplicationDetailsHasuraRequestInputArg}
     * @memberof V1GetApplicationDetailsHasuraRequestInput
     */
    arg?: V1GetApplicationDetailsHasuraRequestInputArg;
}


