/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ExecAction } from './v1-exec-action';
import { V1HTTPGetAction } from './v1-httpget-action';
import { V1TCPSocketAction } from './v1-tcpsocket-action';

/**
 * 
 * @export
 * @interface V1Handler
 */
export interface V1Handler {
    /**
     * 
     * @type {V1ExecAction}
     * @memberof V1Handler
     */
    exec?: V1ExecAction;
    /**
     * 
     * @type {V1HTTPGetAction}
     * @memberof V1Handler
     */
    httpGet?: V1HTTPGetAction;
    /**
     * 
     * @type {V1TCPSocketAction}
     * @memberof V1Handler
     */
    tcpSocket?: V1TCPSocketAction;
}


