/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1HTTPHeader
 */
export interface V1HTTPHeader {
    /**
     * The header field name
     * @type {string}
     * @memberof V1HTTPHeader
     */
    name?: string;
    /**
     * The header field value
     * @type {string}
     * @memberof V1HTTPHeader
     */
    value?: string;
}


