/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1CapsulesStruct } from './v1-capsules-struct';

/**
 * 
 * @export
 * @interface V1InstallCapsulesBody
 */
export interface V1InstallCapsulesBody {
    /**
     * 
     * @type {V1CapsulesStruct}
     * @memberof V1InstallCapsulesBody
     */
    capsules?: V1CapsulesStruct;
    /**
     * 
     * @type {string}
     * @memberof V1InstallCapsulesBody
     */
    clusterName: string;
    /**
     * 
     * @type {string}
     * @memberof V1InstallCapsulesBody
     */
    environment: string;
    /**
     * 
     * @type {string}
     * @memberof V1InstallCapsulesBody
     */
    region: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1InstallCapsulesBody
     */
    wait_for_completion?: boolean;
}


