/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1ObjectFieldSelector
 */
export interface V1ObjectFieldSelector {
    /**
     * Version of the schema the FieldPath is written in terms of, defaults to \"v1\". +optional
     * @type {string}
     * @memberof V1ObjectFieldSelector
     */
    apiVersion?: string;
    /**
     * Path of the field to select in the specified API version.
     * @type {string}
     * @memberof V1ObjectFieldSelector
     */
    fieldPath?: string;
}


