/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1PodCondition
 */
export interface V1PodCondition {
    /**
     * Last time we probed the condition. +optional
     * @type {string}
     * @memberof V1PodCondition
     */
    lastProbeTime?: string;
    /**
     * Last time the condition transitioned from one status to another. +optional
     * @type {string}
     * @memberof V1PodCondition
     */
    lastTransitionTime?: string;
    /**
     * Human-readable message indicating details about last transition. +optional
     * @type {string}
     * @memberof V1PodCondition
     */
    message?: string;
    /**
     * Unique, one-word, CamelCase reason for the condition\'s last transition. +optional
     * @type {string}
     * @memberof V1PodCondition
     */
    reason?: string;
    /**
     * Status is the status of the condition. Can be True, False, Unknown. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
     * @type {string}
     * @memberof V1PodCondition
     */
    status?: string;
    /**
     * Type is the type of the condition. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
     * @type {string}
     * @memberof V1PodCondition
     */
    type?: string;
}


