/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1PersistentVolumeClaimCondition
 */
export interface V1PersistentVolumeClaimCondition {
    /**
     * Last time we probed the condition. +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    lastProbeTime?: string;
    /**
     * Last time the condition transitioned from one status to another. +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    lastTransitionTime?: string;
    /**
     * Human-readable message indicating details about last transition. +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    message?: string;
    /**
     * Unique, this should be a short, machine understandable string that gives the reason for condition\'s last transition. If it reports \"ResizeStarted\" that means the underlying persistent volume is being resized. +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PersistentVolumeClaimCondition
     */
    type?: string;
}


