/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1NodeSelectorTerm } from './v1-node-selector-term';

/**
 * 
 * @export
 * @interface V1PreferredSchedulingTerm
 */
export interface V1PreferredSchedulingTerm {
    /**
     * 
     * @type {V1NodeSelectorTerm}
     * @memberof V1PreferredSchedulingTerm
     */
    preference?: V1NodeSelectorTerm;
    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     * @type {number}
     * @memberof V1PreferredSchedulingTerm
     */
    weight?: number;
}


