/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1PodCondition } from './v1-pod-condition';

/**
 * 
 * @export
 * @interface V1PodStruct
 */
export interface V1PodStruct {
    /**
     * 
     * @type {Array<V1PodCondition>}
     * @memberof V1PodStruct
     */
    Conditions?: Array<V1PodCondition>;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Image?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    ImageTag?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Manifest?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Ready?: string;
    /**
     * 
     * @type {number}
     * @memberof V1PodStruct
     */
    StartTime?: number;
    /**
     * 
     * @type {string}
     * @memberof V1PodStruct
     */
    Status?: string;
}


