/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1SELinuxOptions
 */
export interface V1SELinuxOptions {
    /**
     * Level is SELinux level label that applies to the container. +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    level?: string;
    /**
     * Role is a SELinux role label that applies to the container. +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    role?: string;
    /**
     * Type is a SELinux type label that applies to the container. +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    type?: string;
    /**
     * User is a SELinux user label that applies to the container. +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    user?: string;
}


