/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TypesCluster } from './types-cluster';
import { V1AwsS3Bucket } from './v1-aws-s3-bucket';
import { V1AwsS3StaticSite } from './v1-aws-s3-static-site';
import { V1ElasticSearch } from './v1-elastic-search';
import { V1ElasticacheRedis } from './v1-elasticache-redis';
import { V1EnvironmentRequest } from './v1-environment-request';
import { V1RDS } from './v1-rds';

/**
 * 
 * @export
 * @interface V1TerragruntParserRequestConfig
 */
export interface V1TerragruntParserRequestConfig {
    /**
     * 
     * @type {Array<TypesCluster>}
     * @memberof V1TerragruntParserRequestConfig
     */
    eks?: Array<TypesCluster>;
    /**
     * 
     * @type {Array<V1ElasticSearch>}
     * @memberof V1TerragruntParserRequestConfig
     */
    elastic_search?: Array<V1ElasticSearch>;
    /**
     * 
     * @type {Array<V1ElasticacheRedis>}
     * @memberof V1TerragruntParserRequestConfig
     */
    elasticache_redis?: Array<V1ElasticacheRedis>;
    /**
     * 
     * @type {V1EnvironmentRequest}
     * @memberof V1TerragruntParserRequestConfig
     */
    environment?: V1EnvironmentRequest;
    /**
     * 
     * @type {Array<V1RDS>}
     * @memberof V1TerragruntParserRequestConfig
     */
    rds?: Array<V1RDS>;
    /**
     * 
     * @type {Array<V1AwsS3Bucket>}
     * @memberof V1TerragruntParserRequestConfig
     */
    s3_bucket?: Array<V1AwsS3Bucket>;
    /**
     * 
     * @type {Array<V1AwsS3StaticSite>}
     * @memberof V1TerragruntParserRequestConfig
     */
    s3_static_site?: Array<V1AwsS3StaticSite>;
}


