/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ConfigMapProjection } from './v1-config-map-projection';
import { V1DownwardAPIProjection } from './v1-downward-apiprojection';
import { V1SecretProjection } from './v1-secret-projection';
import { V1ServiceAccountTokenProjection } from './v1-service-account-token-projection';

/**
 * 
 * @export
 * @interface V1VolumeProjection
 */
export interface V1VolumeProjection {
    /**
     * 
     * @type {V1ConfigMapProjection}
     * @memberof V1VolumeProjection
     */
    configMap?: V1ConfigMapProjection;
    /**
     * 
     * @type {V1DownwardAPIProjection}
     * @memberof V1VolumeProjection
     */
    downwardAPI?: V1DownwardAPIProjection;
    /**
     * 
     * @type {V1SecretProjection}
     * @memberof V1VolumeProjection
     */
    secret?: V1SecretProjection;
    /**
     * 
     * @type {V1ServiceAccountTokenProjection}
     * @memberof V1VolumeProjection
     */
    serviceAccountToken?: V1ServiceAccountTokenProjection;
}


