/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1VolumeMount
 */
export interface V1VolumeMount {
    /**
     * Path within the container at which the volume should be mounted.  Must not contain \':\'.
     * @type {string}
     * @memberof V1VolumeMount
     */
    mountPath?: string;
    /**
     * mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationNone is used. This field is beta in 1.10. +optional
     * @type {string}
     * @memberof V1VolumeMount
     */
    mountPropagation?: string;
    /**
     * This must match the Name of a Volume.
     * @type {string}
     * @memberof V1VolumeMount
     */
    name?: string;
    /**
     * Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. +optional
     * @type {boolean}
     * @memberof V1VolumeMount
     */
    readOnly?: boolean;
    /**
     * Path within the volume from which the container\'s volume should be mounted. Defaults to \"\" (volume\'s root). +optional
     * @type {string}
     * @memberof V1VolumeMount
     */
    subPath?: string;
    /**
     * Expanded path within the volume from which the container\'s volume should be mounted. Behaves similarly to SubPath but environment variable references $(VAR_NAME) are expanded using the container\'s environment. Defaults to \"\" (volume\'s root). SubPathExpr and SubPath are mutually exclusive. +optional
     * @type {string}
     * @memberof V1VolumeMount
     */
    subPathExpr?: string;
}


