/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1AWSElasticBlockStoreVolumeSource } from './v1-awselastic-block-store-volume-source';
import { V1AzureDiskVolumeSource } from './v1-azure-disk-volume-source';
import { V1AzureFileVolumeSource } from './v1-azure-file-volume-source';
import { V1CSIVolumeSource } from './v1-csivolume-source';
import { V1CephFSVolumeSource } from './v1-ceph-fsvolume-source';
import { V1CinderVolumeSource } from './v1-cinder-volume-source';
import { V1ConfigMapVolumeSource } from './v1-config-map-volume-source';
import { V1DownwardAPIVolumeSource } from './v1-downward-apivolume-source';
import { V1EmptyDirVolumeSource } from './v1-empty-dir-volume-source';
import { V1EphemeralVolumeSource } from './v1-ephemeral-volume-source';
import { V1FCVolumeSource } from './v1-fcvolume-source';
import { V1FlexVolumeSource } from './v1-flex-volume-source';
import { V1FlockerVolumeSource } from './v1-flocker-volume-source';
import { V1GCEPersistentDiskVolumeSource } from './v1-gcepersistent-disk-volume-source';
import { V1GitRepoVolumeSource } from './v1-git-repo-volume-source';
import { V1GlusterfsVolumeSource } from './v1-glusterfs-volume-source';
import { V1HostPathVolumeSource } from './v1-host-path-volume-source';
import { V1ISCSIVolumeSource } from './v1-iscsivolume-source';
import { V1NFSVolumeSource } from './v1-nfsvolume-source';
import { V1PersistentVolumeClaimVolumeSource } from './v1-persistent-volume-claim-volume-source';
import { V1PhotonPersistentDiskVolumeSource } from './v1-photon-persistent-disk-volume-source';
import { V1PortworxVolumeSource } from './v1-portworx-volume-source';
import { V1ProjectedVolumeSource } from './v1-projected-volume-source';
import { V1QuobyteVolumeSource } from './v1-quobyte-volume-source';
import { V1RBDVolumeSource } from './v1-rbdvolume-source';
import { V1ScaleIOVolumeSource } from './v1-scale-iovolume-source';
import { V1SecretVolumeSource } from './v1-secret-volume-source';
import { V1StorageOSVolumeSource } from './v1-storage-osvolume-source';
import { V1VsphereVirtualDiskVolumeSource } from './v1-vsphere-virtual-disk-volume-source';

/**
 * 
 * @export
 * @interface V1Volume
 */
export interface V1Volume {
    /**
     * 
     * @type {V1AWSElasticBlockStoreVolumeSource}
     * @memberof V1Volume
     */
    awsElasticBlockStore?: V1AWSElasticBlockStoreVolumeSource;
    /**
     * 
     * @type {V1AzureDiskVolumeSource}
     * @memberof V1Volume
     */
    azureDisk?: V1AzureDiskVolumeSource;
    /**
     * 
     * @type {V1AzureFileVolumeSource}
     * @memberof V1Volume
     */
    azureFile?: V1AzureFileVolumeSource;
    /**
     * 
     * @type {V1CephFSVolumeSource}
     * @memberof V1Volume
     */
    cephfs?: V1CephFSVolumeSource;
    /**
     * 
     * @type {V1CinderVolumeSource}
     * @memberof V1Volume
     */
    cinder?: V1CinderVolumeSource;
    /**
     * 
     * @type {V1ConfigMapVolumeSource}
     * @memberof V1Volume
     */
    configMap?: V1ConfigMapVolumeSource;
    /**
     * 
     * @type {V1CSIVolumeSource}
     * @memberof V1Volume
     */
    csi?: V1CSIVolumeSource;
    /**
     * 
     * @type {V1DownwardAPIVolumeSource}
     * @memberof V1Volume
     */
    downwardAPI?: V1DownwardAPIVolumeSource;
    /**
     * 
     * @type {V1EmptyDirVolumeSource}
     * @memberof V1Volume
     */
    emptyDir?: V1EmptyDirVolumeSource;
    /**
     * 
     * @type {V1EphemeralVolumeSource}
     * @memberof V1Volume
     */
    ephemeral?: V1EphemeralVolumeSource;
    /**
     * 
     * @type {V1FCVolumeSource}
     * @memberof V1Volume
     */
    fc?: V1FCVolumeSource;
    /**
     * 
     * @type {V1FlexVolumeSource}
     * @memberof V1Volume
     */
    flexVolume?: V1FlexVolumeSource;
    /**
     * 
     * @type {V1FlockerVolumeSource}
     * @memberof V1Volume
     */
    flocker?: V1FlockerVolumeSource;
    /**
     * 
     * @type {V1GCEPersistentDiskVolumeSource}
     * @memberof V1Volume
     */
    gcePersistentDisk?: V1GCEPersistentDiskVolumeSource;
    /**
     * 
     * @type {V1GitRepoVolumeSource}
     * @memberof V1Volume
     */
    gitRepo?: V1GitRepoVolumeSource;
    /**
     * 
     * @type {V1GlusterfsVolumeSource}
     * @memberof V1Volume
     */
    glusterfs?: V1GlusterfsVolumeSource;
    /**
     * 
     * @type {V1HostPathVolumeSource}
     * @memberof V1Volume
     */
    hostPath?: V1HostPathVolumeSource;
    /**
     * 
     * @type {V1ISCSIVolumeSource}
     * @memberof V1Volume
     */
    iscsi?: V1ISCSIVolumeSource;
    /**
     * Volume\'s name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
     * @type {string}
     * @memberof V1Volume
     */
    name?: string;
    /**
     * 
     * @type {V1NFSVolumeSource}
     * @memberof V1Volume
     */
    nfs?: V1NFSVolumeSource;
    /**
     * 
     * @type {V1PersistentVolumeClaimVolumeSource}
     * @memberof V1Volume
     */
    persistentVolumeClaim?: V1PersistentVolumeClaimVolumeSource;
    /**
     * 
     * @type {V1PhotonPersistentDiskVolumeSource}
     * @memberof V1Volume
     */
    photonPersistentDisk?: V1PhotonPersistentDiskVolumeSource;
    /**
     * 
     * @type {V1PortworxVolumeSource}
     * @memberof V1Volume
     */
    portworxVolume?: V1PortworxVolumeSource;
    /**
     * 
     * @type {V1ProjectedVolumeSource}
     * @memberof V1Volume
     */
    projected?: V1ProjectedVolumeSource;
    /**
     * 
     * @type {V1QuobyteVolumeSource}
     * @memberof V1Volume
     */
    quobyte?: V1QuobyteVolumeSource;
    /**
     * 
     * @type {V1RBDVolumeSource}
     * @memberof V1Volume
     */
    rbd?: V1RBDVolumeSource;
    /**
     * 
     * @type {V1ScaleIOVolumeSource}
     * @memberof V1Volume
     */
    scaleIO?: V1ScaleIOVolumeSource;
    /**
     * 
     * @type {V1SecretVolumeSource}
     * @memberof V1Volume
     */
    secret?: V1SecretVolumeSource;
    /**
     * 
     * @type {V1StorageOSVolumeSource}
     * @memberof V1Volume
     */
    storageos?: V1StorageOSVolumeSource;
    /**
     * 
     * @type {V1VsphereVirtualDiskVolumeSource}
     * @memberof V1Volume
     */
    vsphereVolume?: V1VsphereVirtualDiskVolumeSource;
}


