/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1PodAffinityTerm } from './v1-pod-affinity-term';

/**
 * 
 * @export
 * @interface V1WeightedPodAffinityTerm
 */
export interface V1WeightedPodAffinityTerm {
    /**
     * 
     * @type {V1PodAffinityTerm}
     * @memberof V1WeightedPodAffinityTerm
     */
    podAffinityTerm?: V1PodAffinityTerm;
    /**
     * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
     * @type {number}
     * @memberof V1WeightedPodAffinityTerm
     */
    weight?: number;
}


