/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IntstrIntOrString } from './intstr-int-or-string';

/**
 * 
 * @export
 * @interface V1alpha1Sequence
 */
export interface V1alpha1Sequence {
    /**
     * 
     * @type {IntstrIntOrString}
     * @memberof V1alpha1Sequence
     */
    count?: IntstrIntOrString;
    /**
     * 
     * @type {IntstrIntOrString}
     * @memberof V1alpha1Sequence
     */
    end?: IntstrIntOrString;
    /**
     * Format is a printf format string to format the value in the sequence
     * @type {string}
     * @memberof V1alpha1Sequence
     */
    format?: string;
    /**
     * 
     * @type {IntstrIntOrString}
     * @memberof V1alpha1Sequence
     */
    start?: IntstrIntOrString;
}


