/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1Gauge
 */
export interface V1alpha1Gauge {
    /**
     * Realtime emits this metric in real time if applicable
     * @type {boolean}
     * @memberof V1alpha1Gauge
     */
    realtime?: boolean;
    /**
     * Value is the value of the metric
     * @type {string}
     * @memberof V1alpha1Gauge
     */
    value?: string;
}


