/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1ArtifactRepository } from './v1alpha1-artifact-repository';

/**
 * 
 * @export
 * @interface V1alpha1ArtifactRepositoryRefStatus
 */
export interface V1alpha1ArtifactRepositoryRefStatus {
    /**
     * 
     * @type {V1alpha1ArtifactRepository}
     * @memberof V1alpha1ArtifactRepositoryRefStatus
     */
    artifactRepository?: V1alpha1ArtifactRepository;
    /**
     * The name of the config map. Defaults to \"artifact-repositories\".
     * @type {string}
     * @memberof V1alpha1ArtifactRepositoryRefStatus
     */
    configMap?: string;
    /**
     * If this ref represents the default artifact repository, rather than a config map.
     * @type {boolean}
     * @memberof V1alpha1ArtifactRepositoryRefStatus
     */
    _default?: boolean;
    /**
     * The config map key. Defaults to the value of the \"workflows.argoproj.io/default-artifact-repository\" annotation.
     * @type {string}
     * @memberof V1alpha1ArtifactRepositoryRefStatus
     */
    key?: string;
    /**
     * The namespace of the config map. Defaults to the workflow\'s namespace, or the controller\'s namespace (if found).
     * @type {string}
     * @memberof V1alpha1ArtifactRepositoryRefStatus
     */
    namespace?: string;
}


