/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1VolumeMount } from './v1-volume-mount';
import { V1alpha1ContainerNode } from './v1alpha1-container-node';

/**
 * 
 * @export
 * @interface V1alpha1ContainerSetTemplate
 */
export interface V1alpha1ContainerSetTemplate {
    /**
     * 
     * @type {Array<V1alpha1ContainerNode>}
     * @memberof V1alpha1ContainerSetTemplate
     */
    containers?: Array<V1alpha1ContainerNode>;
    /**
     * 
     * @type {Array<V1VolumeMount>}
     * @memberof V1alpha1ContainerSetTemplate
     */
    volumeMounts?: Array<V1VolumeMount>;
}


