/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ContainerPort } from './v1-container-port';
import { V1EnvFromSource } from './v1-env-from-source';
import { V1EnvVar } from './v1-env-var';
import { V1Lifecycle } from './v1-lifecycle';
import { V1Probe } from './v1-probe';
import { V1ResourceRequirements } from './v1-resource-requirements';
import { V1SecurityContext } from './v1-security-context';
import { V1VolumeDevice } from './v1-volume-device';
import { V1VolumeMount } from './v1-volume-mount';

/**
 * 
 * @export
 * @interface V1alpha1ContainerNode
 */
export interface V1alpha1ContainerNode {
    /**
     * Arguments to the entrypoint. The docker image\'s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell +optional
     * @type {Array<string>}
     * @memberof V1alpha1ContainerNode
     */
    args?: Array<string>;
    /**
     * Entrypoint array. Not executed within a shell. The docker image\'s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container\'s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell +optional
     * @type {Array<string>}
     * @memberof V1alpha1ContainerNode
     */
    command?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1alpha1ContainerNode
     */
    dependencies?: Array<string>;
    /**
     * List of environment variables to set in the container. Cannot be updated. +optional +patchMergeKey=name +patchStrategy=merge
     * @type {Array<V1EnvVar>}
     * @memberof V1alpha1ContainerNode
     */
    env?: Array<V1EnvVar>;
    /**
     * List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated. +optional
     * @type {Array<V1EnvFromSource>}
     * @memberof V1alpha1ContainerNode
     */
    envFrom?: Array<V1EnvFromSource>;
    /**
     * Docker image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets. +optional
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    image?: string;
    /**
     * Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images +optional
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    imagePullPolicy?: string;
    /**
     * 
     * @type {V1Lifecycle}
     * @memberof V1alpha1ContainerNode
     */
    lifecycle?: V1Lifecycle;
    /**
     * 
     * @type {V1Probe}
     * @memberof V1alpha1ContainerNode
     */
    livenessProbe?: V1Probe;
    /**
     * Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    name?: string;
    /**
     * List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Cannot be updated. +optional +patchMergeKey=containerPort +patchStrategy=merge +listType=map +listMapKey=containerPort +listMapKey=protocol
     * @type {Array<V1ContainerPort>}
     * @memberof V1alpha1ContainerNode
     */
    ports?: Array<V1ContainerPort>;
    /**
     * 
     * @type {V1Probe}
     * @memberof V1alpha1ContainerNode
     */
    readinessProbe?: V1Probe;
    /**
     * 
     * @type {V1ResourceRequirements}
     * @memberof V1alpha1ContainerNode
     */
    resources?: V1ResourceRequirements;
    /**
     * 
     * @type {V1SecurityContext}
     * @memberof V1alpha1ContainerNode
     */
    securityContext?: V1SecurityContext;
    /**
     * 
     * @type {V1Probe}
     * @memberof V1alpha1ContainerNode
     */
    startupProbe?: V1Probe;
    /**
     * Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false. +optional
     * @type {boolean}
     * @memberof V1alpha1ContainerNode
     */
    stdin?: boolean;
    /**
     * Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false +optional
     * @type {boolean}
     * @memberof V1alpha1ContainerNode
     */
    stdinOnce?: boolean;
    /**
     * Optional: Path at which the file to which the container\'s termination message will be written is mounted into the container\'s filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated. +optional
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    terminationMessagePath?: string;
    /**
     * Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated. +optional
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    terminationMessagePolicy?: string;
    /**
     * Whether this container should allocate a TTY for itself, also requires \'stdin\' to be true. Default is false. +optional
     * @type {boolean}
     * @memberof V1alpha1ContainerNode
     */
    tty?: boolean;
    /**
     * volumeDevices is the list of block devices to be used by the container. +patchMergeKey=devicePath +patchStrategy=merge +optional
     * @type {Array<V1VolumeDevice>}
     * @memberof V1alpha1ContainerNode
     */
    volumeDevices?: Array<V1VolumeDevice>;
    /**
     * Pod volumes to mount into the container\'s filesystem. Cannot be updated. +optional +patchMergeKey=mountPath +patchStrategy=merge
     * @type {Array<V1VolumeMount>}
     * @memberof V1alpha1ContainerNode
     */
    volumeMounts?: Array<V1VolumeMount>;
    /**
     * Container\'s working directory. If not specified, the container runtime\'s default will be used, which might be configured in the container image. Cannot be updated. +optional
     * @type {string}
     * @memberof V1alpha1ContainerNode
     */
    workingDir?: string;
}


