/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1Counter } from './v1alpha1-counter';
import { V1alpha1Gauge } from './v1alpha1-gauge';
import { V1alpha1Histogram } from './v1alpha1-histogram';
import { V1alpha1MetricLabel } from './v1alpha1-metric-label';

/**
 * 
 * @export
 * @interface V1alpha1Prometheus
 */
export interface V1alpha1Prometheus {
    /**
     * 
     * @type {V1alpha1Counter}
     * @memberof V1alpha1Prometheus
     */
    counter?: V1alpha1Counter;
    /**
     * 
     * @type {V1alpha1Gauge}
     * @memberof V1alpha1Prometheus
     */
    gauge?: V1alpha1Gauge;
    /**
     * Help is a string that describes the metric
     * @type {string}
     * @memberof V1alpha1Prometheus
     */
    help?: string;
    /**
     * 
     * @type {V1alpha1Histogram}
     * @memberof V1alpha1Prometheus
     */
    histogram?: V1alpha1Histogram;
    /**
     * Labels is a list of metric labels
     * @type {Array<V1alpha1MetricLabel>}
     * @memberof V1alpha1Prometheus
     */
    labels?: Array<V1alpha1MetricLabel>;
    /**
     * Name is the name of the metric
     * @type {string}
     * @memberof V1alpha1Prometheus
     */
    name?: string;
    /**
     * When is a conditional statement that decides when to emit the metric
     * @type {string}
     * @memberof V1alpha1Prometheus
     */
    when?: string;
}


