/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1ValueFrom } from './v1alpha1-value-from';

/**
 * 
 * @export
 * @interface V1alpha1Parameter
 */
export interface V1alpha1Parameter {
    /**
     * Default is the default value to use for an input parameter if a value was not supplied
     * @type {string}
     * @memberof V1alpha1Parameter
     */
    _default?: string;
    /**
     * Enum holds a list of string values to choose from, for the actual value of the parameter
     * @type {Array<string>}
     * @memberof V1alpha1Parameter
     */
    _enum?: Array<string>;
    /**
     * GlobalName exports an output parameter to the global scope, making it available as \'{{workflow.outputs.parameters.XXXX}} and in workflow.status.outputs.parameters
     * @type {string}
     * @memberof V1alpha1Parameter
     */
    globalName?: string;
    /**
     * Name is the parameter name
     * @type {string}
     * @memberof V1alpha1Parameter
     */
    name?: string;
    /**
     * Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values
     * @type {string}
     * @memberof V1alpha1Parameter
     */
    value?: string;
    /**
     * 
     * @type {V1alpha1ValueFrom}
     * @memberof V1alpha1Parameter
     */
    valueFrom?: V1alpha1ValueFrom;
}


