/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1ExecutorConfig
 */
export interface V1alpha1ExecutorConfig {
    /**
     * ServiceAccountName specifies the service account name of the executor container.
     * @type {string}
     * @memberof V1alpha1ExecutorConfig
     */
    serviceAccountName?: string;
}


