/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ConfigMapKeySelector } from './v1-config-map-key-selector';

/**
 * 
 * @export
 * @interface V1alpha1Cache
 */
export interface V1alpha1Cache {
    /**
     * 
     * @type {V1ConfigMapKeySelector}
     * @memberof V1alpha1Cache
     */
    configMap?: V1ConfigMapKeySelector;
}


