/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1SemaphoreHolding } from './v1alpha1-semaphore-holding';

/**
 * 
 * @export
 * @interface V1alpha1SemaphoreStatus
 */
export interface V1alpha1SemaphoreStatus {
    /**
     * Holding stores the list of resource acquired synchronization lock for workflows.
     * @type {Array<V1alpha1SemaphoreHolding>}
     * @memberof V1alpha1SemaphoreStatus
     */
    holding?: Array<V1alpha1SemaphoreHolding>;
    /**
     * Waiting indicates the list of current synchronization lock holders.
     * @type {Array<V1alpha1SemaphoreHolding>}
     * @memberof V1alpha1SemaphoreStatus
     */
    waiting?: Array<V1alpha1SemaphoreHolding>;
}


