/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1Cache } from './v1alpha1-cache';

/**
 * 
 * @export
 * @interface V1alpha1Memoize
 */
export interface V1alpha1Memoize {
    /**
     * 
     * @type {V1alpha1Cache}
     * @memberof V1alpha1Memoize
     */
    cache?: V1alpha1Cache;
    /**
     * Key is the key to use as the caching key
     * @type {string}
     * @memberof V1alpha1Memoize
     */
    key?: string;
    /**
     * MaxAge is the maximum age (e.g. \"180s\", \"24h\") of an entry that is still considered valid. If an entry is older than the MaxAge, it will be ignored.
     * @type {string}
     * @memberof V1alpha1Memoize
     */
    maxAge?: string;
}


