/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1Artifact } from './v1alpha1-artifact';
import { V1alpha1Parameter } from './v1alpha1-parameter';

/**
 * 
 * @export
 * @interface V1alpha1Outputs
 */
export interface V1alpha1Outputs {
    /**
     * Artifacts holds the list of output artifacts produced by a step +patchStrategy=merge +patchMergeKey=name
     * @type {Array<V1alpha1Artifact>}
     * @memberof V1alpha1Outputs
     */
    artifacts?: Array<V1alpha1Artifact>;
    /**
     * ExitCode holds the exit code of a script template
     * @type {string}
     * @memberof V1alpha1Outputs
     */
    exitCode?: string;
    /**
     * Parameters holds the list of output parameters produced by a step +patchStrategy=merge +patchMergeKey=name
     * @type {Array<V1alpha1Parameter>}
     * @memberof V1alpha1Outputs
     */
    parameters?: Array<V1alpha1Parameter>;
    /**
     * Result holds the result (stdout) of a script template
     * @type {string}
     * @memberof V1alpha1Outputs
     */
    result?: string;
}


