/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1TarStrategy
 */
export interface V1alpha1TarStrategy {
    /**
     * CompressionLevel specifies the gzip compression level to use for the artifact. Defaults to gzip.DefaultCompression.
     * @type {number}
     * @memberof V1alpha1TarStrategy
     */
    compressionLevel?: number;
}


