/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1MutexStatus } from './v1alpha1-mutex-status';
import { V1alpha1SemaphoreStatus } from './v1alpha1-semaphore-status';

/**
 * 
 * @export
 * @interface V1alpha1SynchronizationStatus
 */
export interface V1alpha1SynchronizationStatus {
    /**
     * 
     * @type {V1alpha1MutexStatus}
     * @memberof V1alpha1SynchronizationStatus
     */
    mutex?: V1alpha1MutexStatus;
    /**
     * 
     * @type {V1alpha1SemaphoreStatus}
     * @memberof V1alpha1SynchronizationStatus
     */
    semaphore?: V1alpha1SemaphoreStatus;
}


