/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1LabelSelector } from './v1-label-selector';

/**
 * 
 * @export
 * @interface V1alpha1PodGC
 */
export interface V1alpha1PodGC {
    /**
     * 
     * @type {V1LabelSelector}
     * @memberof V1alpha1PodGC
     */
    labelSelector?: V1LabelSelector;
    /**
     * Strategy is the strategy to use. One of \"OnPodCompletion\", \"OnPodSuccess\", \"OnWorkflowCompletion\", \"OnWorkflowSuccess\"
     * @type {string}
     * @memberof V1alpha1PodGC
     */
    strategy?: string;
}


