/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1ArtifactoryArtifactRepository } from './v1alpha1-artifactory-artifact-repository';
import { V1alpha1GCSArtifactRepository } from './v1alpha1-gcsartifact-repository';
import { V1alpha1HDFSArtifactRepository } from './v1alpha1-hdfsartifact-repository';
import { V1alpha1OSSArtifactRepository } from './v1alpha1-ossartifact-repository';
import { V1alpha1S3ArtifactRepository } from './v1alpha1-s3-artifact-repository';

/**
 * 
 * @export
 * @interface V1alpha1ArtifactRepository
 */
export interface V1alpha1ArtifactRepository {
    /**
     * ArchiveLogs enables log archiving
     * @type {boolean}
     * @memberof V1alpha1ArtifactRepository
     */
    archiveLogs?: boolean;
    /**
     * 
     * @type {V1alpha1ArtifactoryArtifactRepository}
     * @memberof V1alpha1ArtifactRepository
     */
    artifactory?: V1alpha1ArtifactoryArtifactRepository;
    /**
     * 
     * @type {V1alpha1GCSArtifactRepository}
     * @memberof V1alpha1ArtifactRepository
     */
    gcs?: V1alpha1GCSArtifactRepository;
    /**
     * 
     * @type {V1alpha1HDFSArtifactRepository}
     * @memberof V1alpha1ArtifactRepository
     */
    hdfs?: V1alpha1HDFSArtifactRepository;
    /**
     * 
     * @type {V1alpha1OSSArtifactRepository}
     * @memberof V1alpha1ArtifactRepository
     */
    oss?: V1alpha1OSSArtifactRepository;
    /**
     * 
     * @type {V1alpha1S3ArtifactRepository}
     * @memberof V1alpha1ArtifactRepository
     */
    s3?: V1alpha1S3ArtifactRepository;
}


