/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1Prometheus } from './v1alpha1-prometheus';

/**
 * 
 * @export
 * @interface V1alpha1Metrics
 */
export interface V1alpha1Metrics {
    /**
     * Prometheus is a list of prometheus metrics to be emitted
     * @type {Array<V1alpha1Prometheus>}
     * @memberof V1alpha1Metrics
     */
    prometheus?: Array<V1alpha1Prometheus>;
}


