/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1ArtifactoryArtifact } from './v1alpha1-artifactory-artifact';
import { V1alpha1GCSArtifact } from './v1alpha1-gcsartifact';
import { V1alpha1GitArtifact } from './v1alpha1-git-artifact';
import { V1alpha1HDFSArtifact } from './v1alpha1-hdfsartifact';
import { V1alpha1HTTPArtifact } from './v1alpha1-httpartifact';
import { V1alpha1OSSArtifact } from './v1alpha1-ossartifact';
import { V1alpha1RawArtifact } from './v1alpha1-raw-artifact';
import { V1alpha1S3Artifact } from './v1alpha1-s3-artifact';

/**
 * 
 * @export
 * @interface V1alpha1ArtifactLocation
 */
export interface V1alpha1ArtifactLocation {
    /**
     * ArchiveLogs indicates if the container logs should be archived
     * @type {boolean}
     * @memberof V1alpha1ArtifactLocation
     */
    archiveLogs?: boolean;
    /**
     * 
     * @type {V1alpha1ArtifactoryArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    artifactory?: V1alpha1ArtifactoryArtifact;
    /**
     * 
     * @type {V1alpha1GCSArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    gcs?: V1alpha1GCSArtifact;
    /**
     * 
     * @type {V1alpha1GitArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    git?: V1alpha1GitArtifact;
    /**
     * 
     * @type {V1alpha1HDFSArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    hdfs?: V1alpha1HDFSArtifact;
    /**
     * 
     * @type {V1alpha1HTTPArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    http?: V1alpha1HTTPArtifact;
    /**
     * 
     * @type {V1alpha1OSSArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    oss?: V1alpha1OSSArtifact;
    /**
     * 
     * @type {V1alpha1RawArtifact}
     * @memberof V1alpha1ArtifactLocation
     */
    raw?: V1alpha1RawArtifact;
    /**
     * 
     * @type {V1alpha1S3Artifact}
     * @memberof V1alpha1ArtifactLocation
     */
    s3?: V1alpha1S3Artifact;
}


