/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1TarStrategy } from './v1alpha1-tar-strategy';

/**
 * 
 * @export
 * @interface V1alpha1ArchiveStrategy
 */
export interface V1alpha1ArchiveStrategy {
    /**
     * 
     * @type {object}
     * @memberof V1alpha1ArchiveStrategy
     */
    none?: object;
    /**
     * 
     * @type {V1alpha1TarStrategy}
     * @memberof V1alpha1ArchiveStrategy
     */
    tar?: V1alpha1TarStrategy;
    /**
     * 
     * @type {object}
     * @memberof V1alpha1ArchiveStrategy
     */
    zip?: object;
}


