/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1MutexHolding
 */
export interface V1alpha1MutexHolding {
    /**
     * Holder is a reference to the object which holds the Mutex. Holding Scenario:   1. Current workflow\'s NodeID which is holding the lock.      e.g: ${NodeID} Waiting Scenario:   1. Current workflow or other workflow NodeID which is holding the lock.      e.g: ${WorkflowName}/${NodeID}
     * @type {string}
     * @memberof V1alpha1MutexHolding
     */
    holder?: string;
    /**
     * Reference for the mutex e.g: ${namespace}/mutex/${mutexName}
     * @type {string}
     * @memberof V1alpha1MutexHolding
     */
    mutex?: string;
}


