/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1Artifact } from './v1alpha1-artifact';
import { V1alpha1Parameter } from './v1alpha1-parameter';

/**
 * 
 * @export
 * @interface V1alpha1Arguments
 */
export interface V1alpha1Arguments {
    /**
     * Artifacts is the list of artifacts to pass to the template or workflow +patchStrategy=merge +patchMergeKey=name
     * @type {Array<V1alpha1Artifact>}
     * @memberof V1alpha1Arguments
     */
    artifacts?: Array<V1alpha1Artifact>;
    /**
     * Parameters is the list of parameters to pass to the template or workflow +patchStrategy=merge +patchMergeKey=name
     * @type {Array<V1alpha1Parameter>}
     * @memberof V1alpha1Arguments
     */
    parameters?: Array<V1alpha1Parameter>;
}


