/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1ResourceTemplate
 */
export interface V1alpha1ResourceTemplate {
    /**
     * Action is the action to perform to the resource. Must be one of: get, create, apply, delete, replace, patch
     * @type {string}
     * @memberof V1alpha1ResourceTemplate
     */
    action?: string;
    /**
     * FailureCondition is a label selector expression which describes the conditions of the k8s resource in which the step was considered failed
     * @type {string}
     * @memberof V1alpha1ResourceTemplate
     */
    failureCondition?: string;
    /**
     * Flags is a set of additional options passed to kubectl before submitting a resource I.e. to disable resource validation: flags: [  \"--validate=false\"  # disable resource validation ]
     * @type {Array<string>}
     * @memberof V1alpha1ResourceTemplate
     */
    flags?: Array<string>;
    /**
     * Manifest contains the kubernetes manifest
     * @type {string}
     * @memberof V1alpha1ResourceTemplate
     */
    manifest?: string;
    /**
     * MergeStrategy is the strategy used to merge a patch. It defaults to \"strategic\" Must be one of: strategic, merge, json
     * @type {string}
     * @memberof V1alpha1ResourceTemplate
     */
    mergeStrategy?: string;
    /**
     * SetOwnerReference sets the reference to the workflow on the OwnerReference of generated resource.
     * @type {boolean}
     * @memberof V1alpha1ResourceTemplate
     */
    setOwnerReference?: boolean;
    /**
     * SuccessCondition is a label selector expression which describes the conditions of the k8s resource in which it is acceptable to proceed to the following step
     * @type {string}
     * @memberof V1alpha1ResourceTemplate
     */
    successCondition?: string;
}


