/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SecretKeySelector } from './v1-secret-key-selector';

/**
 * 
 * @export
 * @interface V1alpha1GCSArtifact
 */
export interface V1alpha1GCSArtifact {
    /**
     * Bucket is the name of the bucket
     * @type {string}
     * @memberof V1alpha1GCSArtifact
     */
    bucket?: string;
    /**
     * Key is the path in the bucket where the artifact resides
     * @type {string}
     * @memberof V1alpha1GCSArtifact
     */
    key?: string;
    /**
     * 
     * @type {V1SecretKeySelector}
     * @memberof V1alpha1GCSArtifact
     */
    serviceAccountKeySecret?: V1SecretKeySelector;
}


