/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1HTTPHeaderSource } from './v1alpha1-httpheader-source';

/**
 * 
 * @export
 * @interface V1alpha1HTTPHeader
 */
export interface V1alpha1HTTPHeader {
    /**
     * 
     * @type {string}
     * @memberof V1alpha1HTTPHeader
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1alpha1HTTPHeader
     */
    value?: string;
    /**
     * 
     * @type {V1alpha1HTTPHeaderSource}
     * @memberof V1alpha1HTTPHeader
     */
    valueFrom?: V1alpha1HTTPHeaderSource;
}


