/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1alpha1SemaphoreHolding
 */
export interface V1alpha1SemaphoreHolding {
    /**
     * Holders stores the list of current holder names in the workflow. +listType=atomic
     * @type {Array<string>}
     * @memberof V1alpha1SemaphoreHolding
     */
    holders?: Array<string>;
    /**
     * Semaphore stores the semaphore name.
     * @type {string}
     * @memberof V1alpha1SemaphoreHolding
     */
    semaphore?: string;
}


