/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1ArchiveStrategy } from './v1alpha1-archive-strategy';
import { V1alpha1ArtifactoryArtifact } from './v1alpha1-artifactory-artifact';
import { V1alpha1GCSArtifact } from './v1alpha1-gcsartifact';
import { V1alpha1GitArtifact } from './v1alpha1-git-artifact';
import { V1alpha1HDFSArtifact } from './v1alpha1-hdfsartifact';
import { V1alpha1HTTPArtifact } from './v1alpha1-httpartifact';
import { V1alpha1OSSArtifact } from './v1alpha1-ossartifact';
import { V1alpha1RawArtifact } from './v1alpha1-raw-artifact';
import { V1alpha1S3Artifact } from './v1alpha1-s3-artifact';

/**
 * 
 * @export
 * @interface V1alpha1Artifact
 */
export interface V1alpha1Artifact {
    /**
     * 
     * @type {V1alpha1ArchiveStrategy}
     * @memberof V1alpha1Artifact
     */
    archive?: V1alpha1ArchiveStrategy;
    /**
     * ArchiveLogs indicates if the container logs should be archived
     * @type {boolean}
     * @memberof V1alpha1Artifact
     */
    archiveLogs?: boolean;
    /**
     * 
     * @type {V1alpha1ArtifactoryArtifact}
     * @memberof V1alpha1Artifact
     */
    artifactory?: V1alpha1ArtifactoryArtifact;
    /**
     * From allows an artifact to reference an artifact from a previous step
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    from?: string;
    /**
     * FromExpression, if defined, is evaluated to specify the value for the artifact
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    fromExpression?: string;
    /**
     * 
     * @type {V1alpha1GCSArtifact}
     * @memberof V1alpha1Artifact
     */
    gcs?: V1alpha1GCSArtifact;
    /**
     * 
     * @type {V1alpha1GitArtifact}
     * @memberof V1alpha1Artifact
     */
    git?: V1alpha1GitArtifact;
    /**
     * GlobalName exports an output artifact to the global scope, making it available as \'{{workflow.outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    globalName?: string;
    /**
     * 
     * @type {V1alpha1HDFSArtifact}
     * @memberof V1alpha1Artifact
     */
    hdfs?: V1alpha1HDFSArtifact;
    /**
     * 
     * @type {V1alpha1HTTPArtifact}
     * @memberof V1alpha1Artifact
     */
    http?: V1alpha1HTTPArtifact;
    /**
     * mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts.
     * @type {number}
     * @memberof V1alpha1Artifact
     */
    mode?: number;
    /**
     * name of the artifact. must be unique within a template\'s inputs/outputs.
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    name?: string;
    /**
     * Make Artifacts optional, if Artifacts doesn\'t generate or exist
     * @type {boolean}
     * @memberof V1alpha1Artifact
     */
    optional?: boolean;
    /**
     * 
     * @type {V1alpha1OSSArtifact}
     * @memberof V1alpha1Artifact
     */
    oss?: V1alpha1OSSArtifact;
    /**
     * Path is the container path to the artifact
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    path?: string;
    /**
     * 
     * @type {V1alpha1RawArtifact}
     * @memberof V1alpha1Artifact
     */
    raw?: V1alpha1RawArtifact;
    /**
     * If mode is set, apply the permission recursively into the artifact if it is a folder
     * @type {boolean}
     * @memberof V1alpha1Artifact
     */
    recurseMode?: boolean;
    /**
     * 
     * @type {V1alpha1S3Artifact}
     * @memberof V1alpha1Artifact
     */
    s3?: V1alpha1S3Artifact;
    /**
     * SubPath allows an artifact to be sourced from a subpath within the specified source
     * @type {string}
     * @memberof V1alpha1Artifact
     */
    subPath?: string;
}


