/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1alpha1DataSource } from './v1alpha1-data-source';
import { V1alpha1TransformationStep } from './v1alpha1-transformation-step';

/**
 * 
 * @export
 * @interface V1alpha1Data
 */
export interface V1alpha1Data {
    /**
     * 
     * @type {V1alpha1DataSource}
     * @memberof V1alpha1Data
     */
    source?: V1alpha1DataSource;
    /**
     * Transformation applies a set of transformations
     * @type {Array<V1alpha1TransformationStep>}
     * @memberof V1alpha1Data
     */
    transformation?: Array<V1alpha1TransformationStep>;
}


