/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API Docs
 * This is the docs for midgard api for argonaut
 *
 * The version of the OpenAPI document: 0.4.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IntstrIntOrString } from './intstr-int-or-string';
import { V1LabelSelector } from './v1-label-selector';

/**
 * 
 * @export
 * @interface V1beta1PodDisruptionBudgetSpec
 */
export interface V1beta1PodDisruptionBudgetSpec {
    /**
     * 
     * @type {IntstrIntOrString}
     * @memberof V1beta1PodDisruptionBudgetSpec
     */
    maxUnavailable?: IntstrIntOrString;
    /**
     * 
     * @type {IntstrIntOrString}
     * @memberof V1beta1PodDisruptionBudgetSpec
     */
    minAvailable?: IntstrIntOrString;
    /**
     * 
     * @type {V1LabelSelector}
     * @memberof V1beta1PodDisruptionBudgetSpec
     */
    selector?: V1LabelSelector;
}


